// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.
//
// Glyphs are also under various licenses, as documented here:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/LICENSE
//
// Generated using glyph info from:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/glyphnames.json
//
// Additional information:
//  * Website: https://www.nerdfonts.com
//  * Development Website: https://github.com/ryanoasis/nerd-fonts
//  * Version: 3.4.0

// Package linux contains the Nerd Fonts glyphs for the "linux" class.
package linux

import "github.com/lrstanley/go-nf"

const (
	// Class is the name of the class.
	Class nf.Class = "linux"

	// Version is the version of the Nerd Fonts project which this package was generated from.
	Version = "3.4.0"
)

const (
	Almalinux          nf.Glyph = "" //  ("\uf31d") represents the "linux-almalinux" glyph.
	Alpine             nf.Glyph = "" //  ("\uf300") represents the "linux-alpine" glyph.
	Aosc               nf.Glyph = "" //  ("\uf301") represents the "linux-aosc" glyph.
	Apple              nf.Glyph = "" //  ("\uf302") represents the "linux-apple" glyph.
	Archcraft          nf.Glyph = "" //  ("\uf345") represents the "linux-archcraft" glyph.
	Archlabs           nf.Glyph = "" //  ("\uf31e") represents the "linux-archlabs" glyph.
	Archlinux          nf.Glyph = "" //  ("\uf303") represents the "linux-archlinux" glyph.
	Arcolinux          nf.Glyph = "" //  ("\uf346") represents the "linux-arcolinux" glyph.
	Arduino            nf.Glyph = "" //  ("\uf34b") represents the "linux-arduino" glyph.
	Artix              nf.Glyph = "" //  ("\uf31f") represents the "linux-artix" glyph.
	Awesome            nf.Glyph = "" //  ("\uf354") represents the "linux-awesome" glyph.
	Biglinux           nf.Glyph = "" //  ("\uf347") represents the "linux-biglinux" glyph.
	Bspwm              nf.Glyph = "" //  ("\uf355") represents the "linux-bspwm" glyph.
	Budgie             nf.Glyph = "" //  ("\uf320") represents the "linux-budgie" glyph.
	Centos             nf.Glyph = "" //  ("\uf304") represents the "linux-centos" glyph.
	Cinnamon           nf.Glyph = "" //  ("\uf35f") represents the "linux-cinnamon" glyph.
	Codeberg           nf.Glyph = "" //  ("\uf330") represents the "linux-codeberg" glyph.
	Coreos             nf.Glyph = "" //  ("\uf305") represents the "linux-coreos" glyph.
	Crystal            nf.Glyph = "" //  ("\uf348") represents the "linux-crystal" glyph.
	Debian             nf.Glyph = "" //  ("\uf306") represents the "linux-debian" glyph.
	Deepin             nf.Glyph = "" //  ("\uf321") represents the "linux-deepin" glyph.
	Devuan             nf.Glyph = "" //  ("\uf307") represents the "linux-devuan" glyph.
	Docker             nf.Glyph = "" //  ("\uf308") represents the "linux-docker" glyph.
	Dwm                nf.Glyph = "" //  ("\uf356") represents the "linux-dwm" glyph.
	Elementary         nf.Glyph = "" //  ("\uf309") represents the "linux-elementary" glyph.
	Endeavour          nf.Glyph = "" //  ("\uf322") represents the "linux-endeavour" glyph.
	Enlightenment      nf.Glyph = "" //  ("\uf357") represents the "linux-enlightenment" glyph.
	Fdroid             nf.Glyph = "" //  ("\uf36a") represents the "linux-fdroid" glyph.
	Fedora             nf.Glyph = "" //  ("\uf30a") represents the "linux-fedora" glyph.
	FedoraInverse      nf.Glyph = "" //  ("\uf30b") represents the "linux-fedora_inverse" glyph.
	Ferris             nf.Glyph = "" //  ("\uf323") represents the "linux-ferris" glyph.
	Flathub            nf.Glyph = "" //  ("\uf324") represents the "linux-flathub" glyph.
	Fluxbox            nf.Glyph = "" //  ("\uf358") represents the "linux-fluxbox" glyph.
	Forgejo            nf.Glyph = "" //  ("\uf335") represents the "linux-forgejo" glyph.
	Fosdem             nf.Glyph = "" //  ("\uf36b") represents the "linux-fosdem" glyph.
	Freebsd            nf.Glyph = "" //  ("\uf30c") represents the "linux-freebsd" glyph.
	Freecad            nf.Glyph = "" //  ("\uf336") represents the "linux-freecad" glyph.
	Freedesktop        nf.Glyph = "" //  ("\uf360") represents the "linux-freedesktop" glyph.
	Garuda             nf.Glyph = "" //  ("\uf337") represents the "linux-garuda" glyph.
	Gentoo             nf.Glyph = "" //  ("\uf30d") represents the "linux-gentoo" glyph.
	Gimp               nf.Glyph = "" //  ("\uf338") represents the "linux-gimp" glyph.
	Gitea              nf.Glyph = "" //  ("\uf339") represents the "linux-gitea" glyph.
	Gnome              nf.Glyph = "" //  ("\uf361") represents the "linux-gnome" glyph.
	GnuGuix            nf.Glyph = "" //  ("\uf325") represents the "linux-gnu_guix" glyph.
	Gtk                nf.Glyph = "" //  ("\uf362") represents the "linux-gtk" glyph.
	Hyperbola          nf.Glyph = "" //  ("\uf33a") represents the "linux-hyperbola" glyph.
	Hyprland           nf.Glyph = "" //  ("\uf359") represents the "linux-hyprland" glyph.
	I3                 nf.Glyph = "" //  ("\uf35a") represents the "linux-i3" glyph.
	Illumos            nf.Glyph = "" //  ("\uf326") represents the "linux-illumos" glyph.
	Inkscape           nf.Glyph = "" //  ("\uf33b") represents the "linux-inkscape" glyph.
	Jwm                nf.Glyph = "" //  ("\uf35b") represents the "linux-jwm" glyph.
	KaliLinux          nf.Glyph = "" //  ("\uf327") represents the "linux-kali_linux" glyph.
	Kde                nf.Glyph = "" //  ("\uf373") represents the "linux-kde" glyph.
	KdeNeon            nf.Glyph = "" //  ("\uf331") represents the "linux-kde_neon" glyph.
	KdePlasma          nf.Glyph = "" //  ("\uf332") represents the "linux-kde_plasma" glyph.
	Kdenlive           nf.Glyph = "" //  ("\uf33c") represents the "linux-kdenlive" glyph.
	Kicad              nf.Glyph = "" //  ("\uf34c") represents the "linux-kicad" glyph.
	Krita              nf.Glyph = "" //  ("\uf33d") represents the "linux-krita" glyph.
	Kubuntu            nf.Glyph = "" //  ("\uf333") represents the "linux-kubuntu" glyph.
	KubuntuInverse     nf.Glyph = "" //  ("\uf334") represents the "linux-kubuntu_inverse" glyph.
	Leap               nf.Glyph = "" //  ("\uf37e") represents the "linux-leap" glyph.
	Libreoffice        nf.Glyph = "" //  ("\uf376") represents the "linux-libreoffice" glyph.
	Libreofficebase    nf.Glyph = "" //  ("\uf377") represents the "linux-libreofficebase" glyph.
	Libreofficecalc    nf.Glyph = "" //  ("\uf378") represents the "linux-libreofficecalc" glyph.
	Libreofficedraw    nf.Glyph = "" //  ("\uf379") represents the "linux-libreofficedraw" glyph.
	Libreofficeimpress nf.Glyph = "" //  ("\uf37a") represents the "linux-libreofficeimpress" glyph.
	Libreofficemath    nf.Glyph = "" //  ("\uf37b") represents the "linux-libreofficemath" glyph.
	Libreofficewriter  nf.Glyph = "" //  ("\uf37c") represents the "linux-libreofficewriter" glyph.
	Linuxmint          nf.Glyph = "" //  ("\uf30e") represents the "linux-linuxmint" glyph.
	LinuxmintInverse   nf.Glyph = "" //  ("\uf30f") represents the "linux-linuxmint_inverse" glyph.
	Locos              nf.Glyph = "" //  ("\uf349") represents the "linux-locos" glyph.
	Lxde               nf.Glyph = "" //  ("\uf363") represents the "linux-lxde" glyph.
	Lxle               nf.Glyph = "" //  ("\uf33e") represents the "linux-lxle" glyph.
	Lxqt               nf.Glyph = "" //  ("\uf364") represents the "linux-lxqt" glyph.
	Mageia             nf.Glyph = "" //  ("\uf310") represents the "linux-mageia" glyph.
	Mandriva           nf.Glyph = "" //  ("\uf311") represents the "linux-mandriva" glyph.
	Manjaro            nf.Glyph = "" //  ("\uf312") represents the "linux-manjaro" glyph.
	Mate               nf.Glyph = "" //  ("\uf365") represents the "linux-mate" glyph.
	Mpv                nf.Glyph = "" //  ("\uf36e") represents the "linux-mpv" glyph.
	Mxlinux            nf.Glyph = "" //  ("\uf33f") represents the "linux-mxlinux" glyph.
	Neovim             nf.Glyph = "" //  ("\uf36f") represents the "linux-neovim" glyph.
	Nixos              nf.Glyph = "" //  ("\uf313") represents the "linux-nixos" glyph.
	Nobara             nf.Glyph = "" //  ("\uf380") represents the "linux-nobara" glyph.
	Octoprint          nf.Glyph = "" //  ("\uf34d") represents the "linux-octoprint" glyph.
	Openbsd            nf.Glyph = "" //  ("\uf328") represents the "linux-openbsd" glyph.
	Openscad           nf.Glyph = "" //  ("\uf34e") represents the "linux-openscad" glyph.
	Opensuse           nf.Glyph = "" //  ("\uf314") represents the "linux-opensuse" glyph.
	Osh                nf.Glyph = "" //  ("\uf34f") represents the "linux-osh" glyph.
	Oshwa              nf.Glyph = "" //  ("\uf350") represents the "linux-oshwa" glyph.
	Osi                nf.Glyph = "" //  ("\uf36c") represents the "linux-osi" glyph.
	Parabola           nf.Glyph = "" //  ("\uf340") represents the "linux-parabola" glyph.
	Parrot             nf.Glyph = "" //  ("\uf329") represents the "linux-parrot" glyph.
	PopOs              nf.Glyph = "" //  ("\uf32a") represents the "linux-pop_os" glyph.
	Postmarketos       nf.Glyph = "" //  ("\uf374") represents the "linux-postmarketos" glyph.
	Prusaslicer        nf.Glyph = "" //  ("\uf351") represents the "linux-prusaslicer" glyph.
	Puppy              nf.Glyph = "" //  ("\uf341") represents the "linux-puppy" glyph.
	Qt                 nf.Glyph = "" //  ("\uf375") represents the "linux-qt" glyph.
	Qtile              nf.Glyph = "" //  ("\uf35c") represents the "linux-qtile" glyph.
	Qubesos            nf.Glyph = "" //  ("\uf342") represents the "linux-qubesos" glyph.
	RaspberryPi        nf.Glyph = "" //  ("\uf315") represents the "linux-raspberry_pi" glyph.
	Redhat             nf.Glyph = "" //  ("\uf316") represents the "linux-redhat" glyph.
	Reprap             nf.Glyph = "" //  ("\uf352") represents the "linux-reprap" glyph.
	Riscv              nf.Glyph = "" //  ("\uf353") represents the "linux-riscv" glyph.
	River              nf.Glyph = "" //  ("\uf381") represents the "linux-river" glyph.
	RockyLinux         nf.Glyph = "" //  ("\uf32b") represents the "linux-rocky_linux" glyph.
	Sabayon            nf.Glyph = "" //  ("\uf317") represents the "linux-sabayon" glyph.
	Slackware          nf.Glyph = "" //  ("\uf318") represents the "linux-slackware" glyph.
	SlackwareInverse   nf.Glyph = "" //  ("\uf319") represents the "linux-slackware_inverse" glyph.
	Snappy             nf.Glyph = "" //  ("\uf32c") represents the "linux-snappy" glyph.
	Solus              nf.Glyph = "" //  ("\uf32d") represents the "linux-solus" glyph.
	Sway               nf.Glyph = "" //  ("\uf35d") represents the "linux-sway" glyph.
	Tails              nf.Glyph = "" //  ("\uf343") represents the "linux-tails" glyph.
	Thunderbird        nf.Glyph = "" //  ("\uf370") represents the "linux-thunderbird" glyph.
	Tor                nf.Glyph = "" //  ("\uf371") represents the "linux-tor" glyph.
	Trisquel           nf.Glyph = "" //  ("\uf344") represents the "linux-trisquel" glyph.
	Tumbleweed         nf.Glyph = "" //  ("\uf37d") represents the "linux-tumbleweed" glyph.
	Tux                nf.Glyph = "" //  ("\uf31a") represents the "linux-tux" glyph.
	Typst              nf.Glyph = "" //  ("\uf37f") represents the "linux-typst" glyph.
	Ubuntu             nf.Glyph = "" //  ("\uf31b") represents the "linux-ubuntu" glyph.
	UbuntuInverse      nf.Glyph = "" //  ("\uf31c") represents the "linux-ubuntu_inverse" glyph.
	Vanilla            nf.Glyph = "" //  ("\uf366") represents the "linux-vanilla" glyph.
	Void               nf.Glyph = "" //  ("\uf32e") represents the "linux-void" glyph.
	Vscodium           nf.Glyph = "" //  ("\uf372") represents the "linux-vscodium" glyph.
	Wayland            nf.Glyph = "" //  ("\uf367") represents the "linux-wayland" glyph.
	Wikimedia          nf.Glyph = "" //  ("\uf36d") represents the "linux-wikimedia" glyph.
	Xerolinux          nf.Glyph = "" //  ("\uf34a") represents the "linux-xerolinux" glyph.
	Xfce               nf.Glyph = "" //  ("\uf368") represents the "linux-xfce" glyph.
	Xmonad             nf.Glyph = "" //  ("\uf35e") represents the "linux-xmonad" glyph.
	Xorg               nf.Glyph = "" //  ("\uf369") represents the "linux-xorg" glyph.
	Zorin              nf.Glyph = "" //  ("\uf32f") represents the "linux-zorin" glyph.
)
