// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.

package linux

import (
	"iter"
	"maps"
	"strings"

	"github.com/lrstanley/go-nf"
)

var (
	allGlyphs = map[string]nf.Glyph{
		"almalinux":          Almalinux,
		"alpine":             Alpine,
		"aosc":               Aosc,
		"apple":              Apple,
		"archcraft":          Archcraft,
		"archlabs":           Archlabs,
		"archlinux":          Archlinux,
		"arcolinux":          Arcolinux,
		"arduino":            Arduino,
		"artix":              Artix,
		"awesome":            Awesome,
		"biglinux":           Biglinux,
		"bspwm":              Bspwm,
		"budgie":             Budgie,
		"centos":             Centos,
		"cinnamon":           Cinnamon,
		"codeberg":           Codeberg,
		"coreos":             Coreos,
		"crystal":            Crystal,
		"debian":             Debian,
		"deepin":             Deepin,
		"devuan":             Devuan,
		"docker":             Docker,
		"dwm":                Dwm,
		"elementary":         Elementary,
		"endeavour":          Endeavour,
		"enlightenment":      Enlightenment,
		"fdroid":             Fdroid,
		"fedora":             Fedora,
		"fedora_inverse":     FedoraInverse,
		"ferris":             Ferris,
		"flathub":            Flathub,
		"fluxbox":            Fluxbox,
		"forgejo":            Forgejo,
		"fosdem":             Fosdem,
		"freebsd":            Freebsd,
		"freecad":            Freecad,
		"freedesktop":        Freedesktop,
		"garuda":             Garuda,
		"gentoo":             Gentoo,
		"gimp":               Gimp,
		"gitea":              Gitea,
		"gnome":              Gnome,
		"gnu_guix":           GnuGuix,
		"gtk":                Gtk,
		"hyperbola":          Hyperbola,
		"hyprland":           Hyprland,
		"i3":                 I3,
		"illumos":            Illumos,
		"inkscape":           Inkscape,
		"jwm":                Jwm,
		"kali_linux":         KaliLinux,
		"kde":                Kde,
		"kde_neon":           KdeNeon,
		"kde_plasma":         KdePlasma,
		"kdenlive":           Kdenlive,
		"kicad":              Kicad,
		"krita":              Krita,
		"kubuntu":            Kubuntu,
		"kubuntu_inverse":    KubuntuInverse,
		"leap":               Leap,
		"libreoffice":        Libreoffice,
		"libreofficebase":    Libreofficebase,
		"libreofficecalc":    Libreofficecalc,
		"libreofficedraw":    Libreofficedraw,
		"libreofficeimpress": Libreofficeimpress,
		"libreofficemath":    Libreofficemath,
		"libreofficewriter":  Libreofficewriter,
		"linuxmint":          Linuxmint,
		"linuxmint_inverse":  LinuxmintInverse,
		"locos":              Locos,
		"lxde":               Lxde,
		"lxle":               Lxle,
		"lxqt":               Lxqt,
		"mageia":             Mageia,
		"mandriva":           Mandriva,
		"manjaro":            Manjaro,
		"mate":               Mate,
		"mpv":                Mpv,
		"mxlinux":            Mxlinux,
		"neovim":             Neovim,
		"nixos":              Nixos,
		"nobara":             Nobara,
		"octoprint":          Octoprint,
		"openbsd":            Openbsd,
		"openscad":           Openscad,
		"opensuse":           Opensuse,
		"osh":                Osh,
		"oshwa":              Oshwa,
		"osi":                Osi,
		"parabola":           Parabola,
		"parrot":             Parrot,
		"pop_os":             PopOs,
		"postmarketos":       Postmarketos,
		"prusaslicer":        Prusaslicer,
		"puppy":              Puppy,
		"qt":                 Qt,
		"qtile":              Qtile,
		"qubesos":            Qubesos,
		"raspberry_pi":       RaspberryPi,
		"redhat":             Redhat,
		"reprap":             Reprap,
		"riscv":              Riscv,
		"river":              River,
		"rocky_linux":        RockyLinux,
		"sabayon":            Sabayon,
		"slackware":          Slackware,
		"slackware_inverse":  SlackwareInverse,
		"snappy":             Snappy,
		"solus":              Solus,
		"sway":               Sway,
		"tails":              Tails,
		"thunderbird":        Thunderbird,
		"tor":                Tor,
		"trisquel":           Trisquel,
		"tumbleweed":         Tumbleweed,
		"tux":                Tux,
		"typst":              Typst,
		"ubuntu":             Ubuntu,
		"ubuntu_inverse":     UbuntuInverse,
		"vanilla":            Vanilla,
		"void":               Void,
		"vscodium":           Vscodium,
		"wayland":            Wayland,
		"wikimedia":          Wikimedia,
		"xerolinux":          Xerolinux,
		"xfce":               Xfce,
		"xmonad":             Xmonad,
		"xorg":               Xorg,
		"zorin":              Zorin,
	}
)

// AllGlyphs returns an iterator over all the glyphs in the linux class,
// returned in no particular order.
func AllGlyphs() iter.Seq[nf.Glyph] {
	return maps.Values(allGlyphs)
}

// ByID finds a glyph by its short or full ID within the class, or an empty string
// if the glyph is not found.
func ByID(id string) nf.Glyph {
	if glyph, ok := allGlyphs[id]; ok {
		return glyph
	}
	if _, stripped, ok := strings.Cut(id, string(Class)+"-"); ok {
		if glyph, gok := allGlyphs[stripped]; gok {
			return glyph
		}
	}
	return ""
}

// AllGlyphIDs returns an iterator over all the IDs of the glyphs in the class,
// returned in no particular order.
func AllGlyphIDs() iter.Seq[string] {
	return maps.Keys(allGlyphs)
}

// AllGlyphFullIDs returns an iterator over all the full IDs of the glyphs in
// the class, returned in no particular order.
func AllGlyphFullIDs() iter.Seq[string] {
	return func(yield func(string) bool) {
		for id := range allGlyphs {
			if !yield(string(Class) + "-" + id) {
				return
			}
		}
	}
}
