// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.

// Package nf contains all type-safe glyph constants for the Nerd Fonts project,
// allowing you to access glyphs by their ID, class, or full ID (with various
// helper functions to achieve this).
//
// Take a look at the following sub-packages:
//   - "github.com/lrstanley/go-nf/glyphs/all"
//   - "github.com/lrstanley/go-nf/glyphs/cod"
//   - "github.com/lrstanley/go-nf/glyphs/custom"
//   - "github.com/lrstanley/go-nf/glyphs/dev"
//   - "github.com/lrstanley/go-nf/glyphs/extra"
//   - "github.com/lrstanley/go-nf/glyphs/fa"
//   - "github.com/lrstanley/go-nf/glyphs/fae"
//   - "github.com/lrstanley/go-nf/glyphs/iec"
//   - "github.com/lrstanley/go-nf/glyphs/indent"
//   - "github.com/lrstanley/go-nf/glyphs/indentation"
//   - "github.com/lrstanley/go-nf/glyphs/linux"
//   - "github.com/lrstanley/go-nf/glyphs/md"
//   - "github.com/lrstanley/go-nf/glyphs/oct"
//   - "github.com/lrstanley/go-nf/glyphs/pl"
//   - "github.com/lrstanley/go-nf/glyphs/ple"
//   - "github.com/lrstanley/go-nf/glyphs/pom"
//   - "github.com/lrstanley/go-nf/glyphs/seti"
//   - "github.com/lrstanley/go-nf/glyphs/weather"
package nf

const (
	// Version is the version of the Nerd Fonts project which this package was generated from.
	Version = "3.4.0"
)
