// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.
//
// Glyphs are also under various licenses, as documented here:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/LICENSE
//
// Generated using glyph info from:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/glyphnames.json
//
// Additional information:
//  * Website: https://www.nerdfonts.com
//  * Development Website: https://github.com/ryanoasis/nerd-fonts
//  * Version: 3.4.0

// Package custom contains the Nerd Fonts glyphs for the "custom" class.
package custom

import "github.com/lrstanley/go-nf"

const (
	// Class is the name of the class.
	Class nf.Class = "custom"

	// Version is the version of the Nerd Fonts project which this package was generated from.
	Version = "3.4.0"
)

const (
	Ada             nf.Glyph = "" //  ("\ue6b5") represents the "custom-ada" glyph.
	Asm             nf.Glyph = "" //  ("\ue6ab") represents the "custom-asm" glyph.
	Astro           nf.Glyph = "" //  ("\ue6b3") represents the "custom-astro" glyph.
	Bazel           nf.Glyph = "" //  ("\ue63a") represents the "custom-bazel" glyph.
	C               nf.Glyph = "" //  ("\ue61e") represents the "custom-c" glyph.
	Chuck           nf.Glyph = "" //  ("\ue6b6") represents the "custom-chuck" glyph.
	CommonLisp      nf.Glyph = "" //  ("\ue6b0") represents the "custom-common_lisp" glyph.
	Cpp             nf.Glyph = "" //  ("\ue61d") represents the "custom-cpp" glyph.
	Crystal         nf.Glyph = "" //  ("\ue62f") represents the "custom-crystal" glyph.
	Css             nf.Glyph = "" //  ("\ue6b8") represents the "custom-css" glyph.
	Default         nf.Glyph = "" //  ("\ue612") represents the "custom-default" glyph.
	Electron        nf.Glyph = "" //  ("\ue62e") represents the "custom-electron" glyph.
	Elixir          nf.Glyph = "" //  ("\ue62d") represents the "custom-elixir" glyph.
	Elm             nf.Glyph = "" //  ("\ue62c") represents the "custom-elm" glyph.
	Emacs           nf.Glyph = "" //  ("\ue632") represents the "custom-emacs" glyph.
	Fennel          nf.Glyph = "" //  ("\ue6af") represents the "custom-fennel" glyph.
	Firebase        nf.Glyph = "" //  ("\ue657") represents the "custom-firebase" glyph.
	Folder          nf.Glyph = "" //  ("\ue5ff") represents the "custom-folder" glyph.
	FolderConfig    nf.Glyph = "" //  ("\ue5fc") represents the "custom-folder_config" glyph.
	FolderGit       nf.Glyph = "" //  ("\ue5fb") represents the "custom-folder_git" glyph.
	FolderGitBranch nf.Glyph = "" //  ("\ue5fb") represents the "custom-folder_git_branch" glyph.
	FolderGithub    nf.Glyph = "" //  ("\ue5fd") represents the "custom-folder_github" glyph.
	FolderNpm       nf.Glyph = "" //  ("\ue5fa") represents the "custom-folder_npm" glyph.
	FolderOct       nf.Glyph = "" //  ("\ue6ad") represents the "custom-folder_oct" glyph.
	FolderOpen      nf.Glyph = "" //  ("\ue5fe") represents the "custom-folder_open" glyph.
	Go              nf.Glyph = "" //  ("\ue626") represents the "custom-go" glyph.
	Home            nf.Glyph = "" //  ("\ue617") represents the "custom-home" glyph.
	Kotlin          nf.Glyph = "" //  ("\ue634") represents the "custom-kotlin" glyph.
	Msdos           nf.Glyph = "" //  ("\ue629") represents the "custom-msdos" glyph.
	Neovim          nf.Glyph = "" //  ("\ue6ae") represents the "custom-neovim" glyph.
	Orgmode         nf.Glyph = "" //  ("\ue633") represents the "custom-orgmode" glyph.
	PlayArrow       nf.Glyph = "" //  ("\ue602") represents the "custom-play_arrow" glyph.
	Prettier        nf.Glyph = "" //  ("\ue6b4") represents the "custom-prettier" glyph.
	Puppet          nf.Glyph = "" //  ("\ue631") represents the "custom-puppet" glyph.
	Purescript      nf.Glyph = "" //  ("\ue630") represents the "custom-purescript" glyph.
	Ruby            nf.Glyph = "" //  ("\ue605") represents the "custom-ruby" glyph.
	Scheme          nf.Glyph = "" //  ("\ue6b1") represents the "custom-scheme" glyph.
	Toml            nf.Glyph = "" //  ("\ue6b2") represents the "custom-toml" glyph.
	VLang           nf.Glyph = "" //  ("\ue6ac") represents the "custom-v_lang" glyph.
	Vim             nf.Glyph = "" //  ("\ue62b") represents the "custom-vim" glyph.
	Vitruvian       nf.Glyph = "" //  ("\ue6b7") represents the "custom-vitruvian" glyph.
	Windows         nf.Glyph = "" //  ("\ue62a") represents the "custom-windows" glyph.
)
