// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.
//
// Glyphs are also under various licenses, as documented here:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/LICENSE
//
// Generated using glyph info from:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/glyphnames.json
//
// Additional information:
//  * Website: https://www.nerdfonts.com
//  * Development Website: https://github.com/ryanoasis/nerd-fonts
//  * Version: 3.4.0

// Package weather contains the Nerd Fonts glyphs for the "weather" class.
package weather

import "github.com/lrstanley/go-nf"

const (
	// Class is the name of the class.
	Class nf.Class = "weather"

	// Version is the version of the Nerd Fonts project which this package was generated from.
	Version = "3.4.0"
)

const (
	Alien                    nf.Glyph = "" //  ("\ue36e") represents the "weather-alien" glyph.
	Aliens                   nf.Glyph = "" //  ("\ue345") represents the "weather-aliens" glyph.
	Barometer                nf.Glyph = "" //  ("\ue372") represents the "weather-barometer" glyph.
	Celsius                  nf.Glyph = "" //  ("\ue339") represents the "weather-celsius" glyph.
	Cloud                    nf.Glyph = "" //  ("\ue33d") represents the "weather-cloud" glyph.
	CloudDown                nf.Glyph = "" //  ("\ue33a") represents the "weather-cloud_down" glyph.
	CloudRefresh             nf.Glyph = "" //  ("\ue33b") represents the "weather-cloud_refresh" glyph.
	CloudUp                  nf.Glyph = "" //  ("\ue33c") represents the "weather-cloud_up" glyph.
	Cloudy                   nf.Glyph = "" //  ("\ue312") represents the "weather-cloudy" glyph.
	CloudyGusts              nf.Glyph = "" //  ("\ue310") represents the "weather-cloudy_gusts" glyph.
	CloudyWindy              nf.Glyph = "" //  ("\ue311") represents the "weather-cloudy_windy" glyph.
	DayCloudy                nf.Glyph = "" //  ("\ue302") represents the "weather-day_cloudy" glyph.
	DayCloudyGusts           nf.Glyph = "" //  ("\ue300") represents the "weather-day_cloudy_gusts" glyph.
	DayCloudyHigh            nf.Glyph = "" //  ("\ue376") represents the "weather-day_cloudy_high" glyph.
	DayCloudyWindy           nf.Glyph = "" //  ("\ue301") represents the "weather-day_cloudy_windy" glyph.
	DayFog                   nf.Glyph = "" //  ("\ue303") represents the "weather-day_fog" glyph.
	DayHail                  nf.Glyph = "" //  ("\ue304") represents the "weather-day_hail" glyph.
	DayHaze                  nf.Glyph = "" //  ("\ue3ae") represents the "weather-day_haze" glyph.
	DayLightWind             nf.Glyph = "" //  ("\ue3bc") represents the "weather-day_light_wind" glyph.
	DayLightning             nf.Glyph = "" //  ("\ue305") represents the "weather-day_lightning" glyph.
	DayRain                  nf.Glyph = "" //  ("\ue308") represents the "weather-day_rain" glyph.
	DayRainMix               nf.Glyph = "" //  ("\ue306") represents the "weather-day_rain_mix" glyph.
	DayRainWind              nf.Glyph = "" //  ("\ue307") represents the "weather-day_rain_wind" glyph.
	DayShowers               nf.Glyph = "" //  ("\ue309") represents the "weather-day_showers" glyph.
	DaySleet                 nf.Glyph = "" //  ("\ue3aa") represents the "weather-day_sleet" glyph.
	DaySleetStorm            nf.Glyph = "" //  ("\ue362") represents the "weather-day_sleet_storm" glyph.
	DaySnow                  nf.Glyph = "" //  ("\ue30a") represents the "weather-day_snow" glyph.
	DaySnowThunderstorm      nf.Glyph = "" //  ("\ue365") represents the "weather-day_snow_thunderstorm" glyph.
	DaySnowWind              nf.Glyph = "" //  ("\ue35f") represents the "weather-day_snow_wind" glyph.
	DaySprinkle              nf.Glyph = "" //  ("\ue30b") represents the "weather-day_sprinkle" glyph.
	DayStormShowers          nf.Glyph = "" //  ("\ue30e") represents the "weather-day_storm_showers" glyph.
	DaySunny                 nf.Glyph = "" //  ("\ue30d") represents the "weather-day_sunny" glyph.
	DaySunnyOvercast         nf.Glyph = "" //  ("\ue30c") represents the "weather-day_sunny_overcast" glyph.
	DayThunderstorm          nf.Glyph = "" //  ("\ue30f") represents the "weather-day_thunderstorm" glyph.
	DayWindy                 nf.Glyph = "" //  ("\ue37d") represents the "weather-day_windy" glyph.
	Degrees                  nf.Glyph = "" //  ("\ue33e") represents the "weather-degrees" glyph.
	DirectionDown            nf.Glyph = "" //  ("\ue340") represents the "weather-direction_down" glyph.
	DirectionDownLeft        nf.Glyph = "" //  ("\ue33f") represents the "weather-direction_down_left" glyph.
	DirectionDownRight       nf.Glyph = "" //  ("\ue380") represents the "weather-direction_down_right" glyph.
	DirectionLeft            nf.Glyph = "" //  ("\ue344") represents the "weather-direction_left" glyph.
	DirectionRight           nf.Glyph = "" //  ("\ue349") represents the "weather-direction_right" glyph.
	DirectionUp              nf.Glyph = "" //  ("\ue353") represents the "weather-direction_up" glyph.
	DirectionUpLeft          nf.Glyph = "" //  ("\ue37f") represents the "weather-direction_up_left" glyph.
	DirectionUpRight         nf.Glyph = "" //  ("\ue352") represents the "weather-direction_up_right" glyph.
	Dust                     nf.Glyph = "" //  ("\ue35d") represents the "weather-dust" glyph.
	Earthquake               nf.Glyph = "" //  ("\ue3be") represents the "weather-earthquake" glyph.
	Fahrenheit               nf.Glyph = "" //  ("\ue341") represents the "weather-fahrenheit" glyph.
	Fire                     nf.Glyph = "" //  ("\ue3bf") represents the "weather-fire" glyph.
	Flood                    nf.Glyph = "" //  ("\ue375") represents the "weather-flood" glyph.
	Fog                      nf.Glyph = "" //  ("\ue313") represents the "weather-fog" glyph.
	GaleWarning              nf.Glyph = "" //  ("\ue3c5") represents the "weather-gale_warning" glyph.
	Hail                     nf.Glyph = "" //  ("\ue314") represents the "weather-hail" glyph.
	Horizon                  nf.Glyph = "" //  ("\ue343") represents the "weather-horizon" glyph.
	HorizonAlt               nf.Glyph = "" //  ("\ue342") represents the "weather-horizon_alt" glyph.
	Hot                      nf.Glyph = "" //  ("\ue36b") represents the "weather-hot" glyph.
	Humidity                 nf.Glyph = "" //  ("\ue373") represents the "weather-humidity" glyph.
	Hurricane                nf.Glyph = "" //  ("\ue36c") represents the "weather-hurricane" glyph.
	HurricaneWarning         nf.Glyph = "" //  ("\ue3c7") represents the "weather-hurricane_warning" glyph.
	Lightning                nf.Glyph = "" //  ("\ue315") represents the "weather-lightning" glyph.
	LunarEclipse             nf.Glyph = "" //  ("\ue369") represents the "weather-lunar_eclipse" glyph.
	Meteor                   nf.Glyph = "" //  ("\ue36a") represents the "weather-meteor" glyph.
	MoonAltFirstQuarter      nf.Glyph = "" //  ("\ue3ce") represents the "weather-moon_alt_first_quarter" glyph.
	MoonAltFull              nf.Glyph = "" //  ("\ue3d5") represents the "weather-moon_alt_full" glyph.
	MoonAltNew               nf.Glyph = "" //  ("\ue3e3") represents the "weather-moon_alt_new" glyph.
	MoonAltThirdQuarter      nf.Glyph = "" //  ("\ue3dc") represents the "weather-moon_alt_third_quarter" glyph.
	MoonAltWaningCrescent1   nf.Glyph = "" //  ("\ue3dd") represents the "weather-moon_alt_waning_crescent_1" glyph.
	MoonAltWaningCrescent2   nf.Glyph = "" //  ("\ue3de") represents the "weather-moon_alt_waning_crescent_2" glyph.
	MoonAltWaningCrescent3   nf.Glyph = "" //  ("\ue3df") represents the "weather-moon_alt_waning_crescent_3" glyph.
	MoonAltWaningCrescent4   nf.Glyph = "" //  ("\ue3e0") represents the "weather-moon_alt_waning_crescent_4" glyph.
	MoonAltWaningCrescent5   nf.Glyph = "" //  ("\ue3e1") represents the "weather-moon_alt_waning_crescent_5" glyph.
	MoonAltWaningCrescent6   nf.Glyph = "" //  ("\ue3e2") represents the "weather-moon_alt_waning_crescent_6" glyph.
	MoonAltWaningGibbous1    nf.Glyph = "" //  ("\ue3d6") represents the "weather-moon_alt_waning_gibbous_1" glyph.
	MoonAltWaningGibbous2    nf.Glyph = "" //  ("\ue3d7") represents the "weather-moon_alt_waning_gibbous_2" glyph.
	MoonAltWaningGibbous3    nf.Glyph = "" //  ("\ue3d8") represents the "weather-moon_alt_waning_gibbous_3" glyph.
	MoonAltWaningGibbous4    nf.Glyph = "" //  ("\ue3d9") represents the "weather-moon_alt_waning_gibbous_4" glyph.
	MoonAltWaningGibbous5    nf.Glyph = "" //  ("\ue3da") represents the "weather-moon_alt_waning_gibbous_5" glyph.
	MoonAltWaningGibbous6    nf.Glyph = "" //  ("\ue3db") represents the "weather-moon_alt_waning_gibbous_6" glyph.
	MoonAltWaxingCrescent1   nf.Glyph = "" //  ("\ue3c8") represents the "weather-moon_alt_waxing_crescent_1" glyph.
	MoonAltWaxingCrescent2   nf.Glyph = "" //  ("\ue3c9") represents the "weather-moon_alt_waxing_crescent_2" glyph.
	MoonAltWaxingCrescent3   nf.Glyph = "" //  ("\ue3ca") represents the "weather-moon_alt_waxing_crescent_3" glyph.
	MoonAltWaxingCrescent4   nf.Glyph = "" //  ("\ue3cb") represents the "weather-moon_alt_waxing_crescent_4" glyph.
	MoonAltWaxingCrescent5   nf.Glyph = "" //  ("\ue3cc") represents the "weather-moon_alt_waxing_crescent_5" glyph.
	MoonAltWaxingCrescent6   nf.Glyph = "" //  ("\ue3cd") represents the "weather-moon_alt_waxing_crescent_6" glyph.
	MoonAltWaxingGibbous1    nf.Glyph = "" //  ("\ue3cf") represents the "weather-moon_alt_waxing_gibbous_1" glyph.
	MoonAltWaxingGibbous2    nf.Glyph = "" //  ("\ue3d0") represents the "weather-moon_alt_waxing_gibbous_2" glyph.
	MoonAltWaxingGibbous3    nf.Glyph = "" //  ("\ue3d1") represents the "weather-moon_alt_waxing_gibbous_3" glyph.
	MoonAltWaxingGibbous4    nf.Glyph = "" //  ("\ue3d2") represents the "weather-moon_alt_waxing_gibbous_4" glyph.
	MoonAltWaxingGibbous5    nf.Glyph = "" //  ("\ue3d3") represents the "weather-moon_alt_waxing_gibbous_5" glyph.
	MoonAltWaxingGibbous6    nf.Glyph = "" //  ("\ue3d4") represents the "weather-moon_alt_waxing_gibbous_6" glyph.
	MoonFirstQuarter         nf.Glyph = "" //  ("\ue394") represents the "weather-moon_first_quarter" glyph.
	MoonFull                 nf.Glyph = "" //  ("\ue39b") represents the "weather-moon_full" glyph.
	MoonNew                  nf.Glyph = "" //  ("\ue38d") represents the "weather-moon_new" glyph.
	MoonThirdQuarter         nf.Glyph = "" //  ("\ue3a2") represents the "weather-moon_third_quarter" glyph.
	MoonWaningCrescent1      nf.Glyph = "" //  ("\ue3a3") represents the "weather-moon_waning_crescent_1" glyph.
	MoonWaningCrescent2      nf.Glyph = "" //  ("\ue3a4") represents the "weather-moon_waning_crescent_2" glyph.
	MoonWaningCrescent3      nf.Glyph = "" //  ("\ue3a5") represents the "weather-moon_waning_crescent_3" glyph.
	MoonWaningCrescent4      nf.Glyph = "" //  ("\ue3a6") represents the "weather-moon_waning_crescent_4" glyph.
	MoonWaningCrescent5      nf.Glyph = "" //  ("\ue3a7") represents the "weather-moon_waning_crescent_5" glyph.
	MoonWaningCrescent6      nf.Glyph = "" //  ("\ue3a8") represents the "weather-moon_waning_crescent_6" glyph.
	MoonWaningGibbous1       nf.Glyph = "" //  ("\ue39c") represents the "weather-moon_waning_gibbous_1" glyph.
	MoonWaningGibbous2       nf.Glyph = "" //  ("\ue39d") represents the "weather-moon_waning_gibbous_2" glyph.
	MoonWaningGibbous3       nf.Glyph = "" //  ("\ue39e") represents the "weather-moon_waning_gibbous_3" glyph.
	MoonWaningGibbous4       nf.Glyph = "" //  ("\ue39f") represents the "weather-moon_waning_gibbous_4" glyph.
	MoonWaningGibbous5       nf.Glyph = "" //  ("\ue3a0") represents the "weather-moon_waning_gibbous_5" glyph.
	MoonWaningGibbous6       nf.Glyph = "" //  ("\ue3a1") represents the "weather-moon_waning_gibbous_6" glyph.
	MoonWaxingCrescent1      nf.Glyph = "" //  ("\ue38e") represents the "weather-moon_waxing_crescent_1" glyph.
	MoonWaxingCrescent2      nf.Glyph = "" //  ("\ue38f") represents the "weather-moon_waxing_crescent_2" glyph.
	MoonWaxingCrescent3      nf.Glyph = "" //  ("\ue390") represents the "weather-moon_waxing_crescent_3" glyph.
	MoonWaxingCrescent4      nf.Glyph = "" //  ("\ue391") represents the "weather-moon_waxing_crescent_4" glyph.
	MoonWaxingCrescent5      nf.Glyph = "" //  ("\ue392") represents the "weather-moon_waxing_crescent_5" glyph.
	MoonWaxingCrescent6      nf.Glyph = "" //  ("\ue393") represents the "weather-moon_waxing_crescent_6" glyph.
	MoonWaxingGibbous1       nf.Glyph = "" //  ("\ue395") represents the "weather-moon_waxing_gibbous_1" glyph.
	MoonWaxingGibbous2       nf.Glyph = "" //  ("\ue396") represents the "weather-moon_waxing_gibbous_2" glyph.
	MoonWaxingGibbous3       nf.Glyph = "" //  ("\ue397") represents the "weather-moon_waxing_gibbous_3" glyph.
	MoonWaxingGibbous4       nf.Glyph = "" //  ("\ue398") represents the "weather-moon_waxing_gibbous_4" glyph.
	MoonWaxingGibbous5       nf.Glyph = "" //  ("\ue399") represents the "weather-moon_waxing_gibbous_5" glyph.
	MoonWaxingGibbous6       nf.Glyph = "" //  ("\ue39a") represents the "weather-moon_waxing_gibbous_6" glyph.
	Moonrise                 nf.Glyph = "" //  ("\ue3c1") represents the "weather-moonrise" glyph.
	Moonset                  nf.Glyph = "" //  ("\ue3c2") represents the "weather-moonset" glyph.
	Na                       nf.Glyph = "" //  ("\ue374") represents the "weather-na" glyph.
	NightAltCloudy           nf.Glyph = "" //  ("\ue37e") represents the "weather-night_alt_cloudy" glyph.
	NightAltCloudyGusts      nf.Glyph = "" //  ("\ue31f") represents the "weather-night_alt_cloudy_gusts" glyph.
	NightAltCloudyHigh       nf.Glyph = "" //  ("\ue377") represents the "weather-night_alt_cloudy_high" glyph.
	NightAltCloudyWindy      nf.Glyph = "" //  ("\ue320") represents the "weather-night_alt_cloudy_windy" glyph.
	NightAltHail             nf.Glyph = "" //  ("\ue321") represents the "weather-night_alt_hail" glyph.
	NightAltLightning        nf.Glyph = "" //  ("\ue322") represents the "weather-night_alt_lightning" glyph.
	NightAltPartlyCloudy     nf.Glyph = "" //  ("\ue379") represents the "weather-night_alt_partly_cloudy" glyph.
	NightAltRain             nf.Glyph = "" //  ("\ue325") represents the "weather-night_alt_rain" glyph.
	NightAltRainMix          nf.Glyph = "" //  ("\ue323") represents the "weather-night_alt_rain_mix" glyph.
	NightAltRainWind         nf.Glyph = "" //  ("\ue324") represents the "weather-night_alt_rain_wind" glyph.
	NightAltShowers          nf.Glyph = "" //  ("\ue326") represents the "weather-night_alt_showers" glyph.
	NightAltSleet            nf.Glyph = "" //  ("\ue3ac") represents the "weather-night_alt_sleet" glyph.
	NightAltSleetStorm       nf.Glyph = "" //  ("\ue364") represents the "weather-night_alt_sleet_storm" glyph.
	NightAltSnow             nf.Glyph = "" //  ("\ue327") represents the "weather-night_alt_snow" glyph.
	NightAltSnowThunderstorm nf.Glyph = "" //  ("\ue367") represents the "weather-night_alt_snow_thunderstorm" glyph.
	NightAltSnowWind         nf.Glyph = "" //  ("\ue361") represents the "weather-night_alt_snow_wind" glyph.
	NightAltSprinkle         nf.Glyph = "" //  ("\ue328") represents the "weather-night_alt_sprinkle" glyph.
	NightAltStormShowers     nf.Glyph = "" //  ("\ue329") represents the "weather-night_alt_storm_showers" glyph.
	NightAltThunderstorm     nf.Glyph = "" //  ("\ue32a") represents the "weather-night_alt_thunderstorm" glyph.
	NightClear               nf.Glyph = "" //  ("\ue32b") represents the "weather-night_clear" glyph.
	NightCloudy              nf.Glyph = "" //  ("\ue32e") represents the "weather-night_cloudy" glyph.
	NightCloudyGusts         nf.Glyph = "" //  ("\ue32c") represents the "weather-night_cloudy_gusts" glyph.
	NightCloudyHigh          nf.Glyph = "" //  ("\ue378") represents the "weather-night_cloudy_high" glyph.
	NightCloudyWindy         nf.Glyph = "" //  ("\ue32d") represents the "weather-night_cloudy_windy" glyph.
	NightFog                 nf.Glyph = "" //  ("\ue346") represents the "weather-night_fog" glyph.
	NightHail                nf.Glyph = "" //  ("\ue32f") represents the "weather-night_hail" glyph.
	NightLightning           nf.Glyph = "" //  ("\ue330") represents the "weather-night_lightning" glyph.
	NightPartlyCloudy        nf.Glyph = "" //  ("\ue37b") represents the "weather-night_partly_cloudy" glyph.
	NightRain                nf.Glyph = "" //  ("\ue333") represents the "weather-night_rain" glyph.
	NightRainMix             nf.Glyph = "" //  ("\ue331") represents the "weather-night_rain_mix" glyph.
	NightRainWind            nf.Glyph = "" //  ("\ue332") represents the "weather-night_rain_wind" glyph.
	NightShowers             nf.Glyph = "" //  ("\ue334") represents the "weather-night_showers" glyph.
	NightSleet               nf.Glyph = "" //  ("\ue3ab") represents the "weather-night_sleet" glyph.
	NightSleetStorm          nf.Glyph = "" //  ("\ue363") represents the "weather-night_sleet_storm" glyph.
	NightSnow                nf.Glyph = "" //  ("\ue335") represents the "weather-night_snow" glyph.
	NightSnowThunderstorm    nf.Glyph = "" //  ("\ue366") represents the "weather-night_snow_thunderstorm" glyph.
	NightSnowWind            nf.Glyph = "" //  ("\ue360") represents the "weather-night_snow_wind" glyph.
	NightSprinkle            nf.Glyph = "" //  ("\ue336") represents the "weather-night_sprinkle" glyph.
	NightStormShowers        nf.Glyph = "" //  ("\ue337") represents the "weather-night_storm_showers" glyph.
	NightThunderstorm        nf.Glyph = "" //  ("\ue338") represents the "weather-night_thunderstorm" glyph.
	Rain                     nf.Glyph = "" //  ("\ue318") represents the "weather-rain" glyph.
	RainMix                  nf.Glyph = "" //  ("\ue316") represents the "weather-rain_mix" glyph.
	RainWind                 nf.Glyph = "" //  ("\ue317") represents the "weather-rain_wind" glyph.
	Raindrop                 nf.Glyph = "" //  ("\ue371") represents the "weather-raindrop" glyph.
	Raindrops                nf.Glyph = "" //  ("\ue34a") represents the "weather-raindrops" glyph.
	Refresh                  nf.Glyph = "" //  ("\ue348") represents the "weather-refresh" glyph.
	RefreshAlt               nf.Glyph = "" //  ("\ue347") represents the "weather-refresh_alt" glyph.
	Sandstorm                nf.Glyph = "" //  ("\ue37a") represents the "weather-sandstorm" glyph.
	Showers                  nf.Glyph = "" //  ("\ue319") represents the "weather-showers" glyph.
	Sleet                    nf.Glyph = "" //  ("\ue3ad") represents the "weather-sleet" glyph.
	SmallCraftAdvisory       nf.Glyph = "" //  ("\ue3c4") represents the "weather-small_craft_advisory" glyph.
	Smog                     nf.Glyph = "" //  ("\ue36d") represents the "weather-smog" glyph.
	Smoke                    nf.Glyph = "" //  ("\ue35c") represents the "weather-smoke" glyph.
	Snow                     nf.Glyph = "" //  ("\ue31a") represents the "weather-snow" glyph.
	SnowWind                 nf.Glyph = "" //  ("\ue35e") represents the "weather-snow_wind" glyph.
	SnowflakeCold            nf.Glyph = "" //  ("\ue36f") represents the "weather-snowflake_cold" glyph.
	SolarEclipse             nf.Glyph = "" //  ("\ue368") represents the "weather-solar_eclipse" glyph.
	Sprinkle                 nf.Glyph = "" //  ("\ue31b") represents the "weather-sprinkle" glyph.
	Stars                    nf.Glyph = "" //  ("\ue370") represents the "weather-stars" glyph.
	StormShowers             nf.Glyph = "" //  ("\ue31c") represents the "weather-storm_showers" glyph.
	StormWarning             nf.Glyph = "" //  ("\ue3c6") represents the "weather-storm_warning" glyph.
	StrongWind               nf.Glyph = "" //  ("\ue34b") represents the "weather-strong_wind" glyph.
	Sunrise                  nf.Glyph = "" //  ("\ue34c") represents the "weather-sunrise" glyph.
	Sunset                   nf.Glyph = "" //  ("\ue34d") represents the "weather-sunset" glyph.
	Thermometer              nf.Glyph = "" //  ("\ue350") represents the "weather-thermometer" glyph.
	ThermometerExterior      nf.Glyph = "" //  ("\ue34e") represents the "weather-thermometer_exterior" glyph.
	ThermometerInternal      nf.Glyph = "" //  ("\ue34f") represents the "weather-thermometer_internal" glyph.
	Thunderstorm             nf.Glyph = "" //  ("\ue31d") represents the "weather-thunderstorm" glyph.
	Time1                    nf.Glyph = "" //  ("\ue382") represents the "weather-time_1" glyph.
	Time10                   nf.Glyph = "" //  ("\ue38b") represents the "weather-time_10" glyph.
	Time11                   nf.Glyph = "" //  ("\ue38c") represents the "weather-time_11" glyph.
	Time12                   nf.Glyph = "" //  ("\ue381") represents the "weather-time_12" glyph.
	Time2                    nf.Glyph = "" //  ("\ue383") represents the "weather-time_2" glyph.
	Time3                    nf.Glyph = "" //  ("\ue384") represents the "weather-time_3" glyph.
	Time4                    nf.Glyph = "" //  ("\ue385") represents the "weather-time_4" glyph.
	Time5                    nf.Glyph = "" //  ("\ue386") represents the "weather-time_5" glyph.
	Time6                    nf.Glyph = "" //  ("\ue387") represents the "weather-time_6" glyph.
	Time7                    nf.Glyph = "" //  ("\ue388") represents the "weather-time_7" glyph.
	Time8                    nf.Glyph = "" //  ("\ue389") represents the "weather-time_8" glyph.
	Time9                    nf.Glyph = "" //  ("\ue38a") represents the "weather-time_9" glyph.
	Tornado                  nf.Glyph = "" //  ("\ue351") represents the "weather-tornado" glyph.
	Train                    nf.Glyph = "" //  ("\ue3c3") represents the "weather-train" glyph.
	Tsunami                  nf.Glyph = "" //  ("\ue3bd") represents the "weather-tsunami" glyph.
	Umbrella                 nf.Glyph = "" //  ("\ue37c") represents the "weather-umbrella" glyph.
	Volcano                  nf.Glyph = "" //  ("\ue3c0") represents the "weather-volcano" glyph.
	WindBeaufort0            nf.Glyph = "" //  ("\ue3af") represents the "weather-wind_beaufort_0" glyph.
	WindBeaufort1            nf.Glyph = "" //  ("\ue3b0") represents the "weather-wind_beaufort_1" glyph.
	WindBeaufort10           nf.Glyph = "" //  ("\ue3b9") represents the "weather-wind_beaufort_10" glyph.
	WindBeaufort11           nf.Glyph = "" //  ("\ue3ba") represents the "weather-wind_beaufort_11" glyph.
	WindBeaufort12           nf.Glyph = "" //  ("\ue3bb") represents the "weather-wind_beaufort_12" glyph.
	WindBeaufort2            nf.Glyph = "" //  ("\ue3b1") represents the "weather-wind_beaufort_2" glyph.
	WindBeaufort3            nf.Glyph = "" //  ("\ue3b2") represents the "weather-wind_beaufort_3" glyph.
	WindBeaufort4            nf.Glyph = "" //  ("\ue3b3") represents the "weather-wind_beaufort_4" glyph.
	WindBeaufort5            nf.Glyph = "" //  ("\ue3b4") represents the "weather-wind_beaufort_5" glyph.
	WindBeaufort6            nf.Glyph = "" //  ("\ue3b5") represents the "weather-wind_beaufort_6" glyph.
	WindBeaufort7            nf.Glyph = "" //  ("\ue3b6") represents the "weather-wind_beaufort_7" glyph.
	WindBeaufort8            nf.Glyph = "" //  ("\ue3b7") represents the "weather-wind_beaufort_8" glyph.
	WindBeaufort9            nf.Glyph = "" //  ("\ue3b8") represents the "weather-wind_beaufort_9" glyph.
	WindDirection            nf.Glyph = "" //  ("\ue3a9") represents the "weather-wind_direction" glyph.
	WindEast                 nf.Glyph = "" //  ("\ue35b") represents the "weather-wind_east" glyph.
	WindNorth                nf.Glyph = "" //  ("\ue35a") represents the "weather-wind_north" glyph.
	WindNorthEast            nf.Glyph = "" //  ("\ue359") represents the "weather-wind_north_east" glyph.
	WindNorthWest            nf.Glyph = "" //  ("\ue358") represents the "weather-wind_north_west" glyph.
	WindSouth                nf.Glyph = "" //  ("\ue357") represents the "weather-wind_south" glyph.
	WindSouthEast            nf.Glyph = "" //  ("\ue356") represents the "weather-wind_south_east" glyph.
	WindSouthWest            nf.Glyph = "" //  ("\ue355") represents the "weather-wind_south_west" glyph.
	WindWest                 nf.Glyph = "" //  ("\ue354") represents the "weather-wind_west" glyph.
	Windy                    nf.Glyph = "" //  ("\ue31e") represents the "weather-windy" glyph.
)
