// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.

package indentation

import (
	"iter"
	"maps"
	"strings"

	"github.com/lrstanley/go-nf"
)

var (
	allGlyphs = map[string]nf.Glyph{
		"line": Line,
	}
)

// AllGlyphs returns an iterator over all the glyphs in the indentation class,
// returned in no particular order.
func AllGlyphs() iter.Seq[nf.Glyph] {
	return maps.Values(allGlyphs)
}

// ByID finds a glyph by its short or full ID within the class, or an empty string
// if the glyph is not found.
func ByID(id string) nf.Glyph {
	if glyph, ok := allGlyphs[id]; ok {
		return glyph
	}
	if _, stripped, ok := strings.Cut(id, string(Class)+"-"); ok {
		if glyph, gok := allGlyphs[stripped]; gok {
			return glyph
		}
	}
	return ""
}

// AllGlyphIDs returns an iterator over all the IDs of the glyphs in the class,
// returned in no particular order.
func AllGlyphIDs() iter.Seq[string] {
	return maps.Keys(allGlyphs)
}

// AllGlyphFullIDs returns an iterator over all the full IDs of the glyphs in
// the class, returned in no particular order.
func AllGlyphFullIDs() iter.Seq[string] {
	return func(yield func(string) bool) {
		for id := range allGlyphs {
			if !yield(string(Class) + "-" + id) {
				return
			}
		}
	}
}
