// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.
//
// Glyphs are also under various licenses, as documented here:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/LICENSE
//
// Generated using glyph info from:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/glyphnames.json
//
// Additional information:
//  * Website: https://www.nerdfonts.com
//  * Development Website: https://github.com/ryanoasis/nerd-fonts
//  * Version: 3.4.0

// Package indent contains the Nerd Fonts glyphs for the "indent" class.
package indent

import "github.com/lrstanley/go-nf"

const (
	// ClassName is the name of the class.
	ClassName = "indent"

	// Version is the version of the Nerd Fonts project which this package was generated from.
	Version = "3.4.0"
)

// DottedGuide () represents the "indent-dotted_guide" glyph.
var DottedGuide = &nf.Glyph{
	ID:      "dotted_guide",
	Class:   ClassName,
	Char:    "",
	Unicode: "\ue621",
}

// Line () represents the "indent-line" glyph.
var Line = &nf.Glyph{
	ID:      "line",
	Class:   ClassName,
	Char:    "",
	Unicode: "\ue621",
}
