// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.

package fae

import (
	"iter"
	"slices"

	"github.com/lrstanley/go-nf"
)

var allGlyphs = []*nf.Glyph{
	AppleFruit,
	Atom,
	Bacteria,
	Banana,
	Bath,
	Bed,
	Benzene,
	Bigger,
	Biohazard,
	BloggerCircle,
	BloggerSquare,
	Bones,
	BookOpen,
	BookOpenO,
	Brain,
	Bread,
	Butterfly,
	Carot,
	CcBy,
	CcCc,
	CcNc,
	CcNcEu,
	CcNcJp,
	CcNd,
	CcRemix,
	CcSa,
	CcShare,
	CcZero,
	ChecklistO,
	Cheese,
	Cherry,
	ChessBishop,
	ChessHorse,
	ChessKing,
	ChessPawn,
	ChessQueen,
	ChessTower,
	ChickenThigh,
	Chilli,
	Chip,
	Cicling,
	Cloud,
	Cockroach,
	CoffeBeans,
	Coins,
	Comb,
	Comet,
	Crown,
	CupCoffe,
	Dice,
	Disco,
	Dna,
	Donut,
	Dress,
	Drop,
	Ello,
	EnvelopeOpen,
	EnvelopeOpenO,
	Equal,
	EqualBigger,
	Feedly,
	FileExport,
	FileImport,
	Fingerprint,
	Floppy,
	Footprint,
	Freecodecamp,
	Galaxy,
	Galery,
	GiftCard,
	Glass,
	GoogleDrive,
	GooglePlay,
	Gps,
	Grav,
	Guitar,
	Gut,
	Halter,
	Hamburger,
	Hat,
	Hexagon,
	HighHeel,
	Hotdog,
	IceCream,
	IdCard,
	Imdb,
	Infinity,
	Injection,
	Isle,
	Java,
	Layers,
	Lips,
	Lipstick,
	Liver,
	Lollipop,
	LoyaltyCard,
	Lung,
	MakeupBrushes,
	Maximize,
	Meat,
	Medicine,
	Microscope,
	MilkBottle,
	Minimize,
	Molecule,
	MoonCloud,
	Mountains,
	Mushroom,
	Mustache,
	Mysql,
	Nintendo,
	Orange,
	PaletteColor,
	Peach,
	Pear,
	Pi,
	Pizza,
	Planet,
	Plant,
	Playstation,
	Poison,
	Popcorn,
	Popsicle,
	Pulse,
	Python,
	QuoraCircle,
	QuoraSquare,
	Radioactive,
	Raining,
	RealHeart,
	Refrigerator,
	Restore,
	Ring,
	Ruby,
	RubyO,
	Ruler,
	Shirt,
	Slash,
	Smaller,
	Snowing,
	Soda,
	Sofa,
	Soup,
	Spermatozoon,
	SpinDouble,
	Stomach,
	Storm,
	SunCloud,
	Sushi,
	Tacos,
	Telegram,
	TelegramCircle,
	Telescope,
	Thermometer,
	ThermometerHigh,
	ThermometerLow,
	ThinClose,
	Toilet,
	Tools,
	Tooth,
	Tree,
	TriangleRuler,
	Umbrella,
	Uterus,
	Virus,
	W3C,
	Walking,
	Wallet,
	Wind,
	Xbox,
}

// AllGlyphs returns an iterator over all the glyphs in the fae class.
func AllGlyphs() iter.Seq[*nf.Glyph] {
	return slices.Values(allGlyphs)
}

// ByID finds a glyph by its ID within the class.
func ByID(id string) *nf.Glyph {
	switch id {
	case "apple_fruit", "fae-apple_fruit":
		return AppleFruit
	case "atom", "fae-atom":
		return Atom
	case "bacteria", "fae-bacteria":
		return Bacteria
	case "banana", "fae-banana":
		return Banana
	case "bath", "fae-bath":
		return Bath
	case "bed", "fae-bed":
		return Bed
	case "benzene", "fae-benzene":
		return Benzene
	case "bigger", "fae-bigger":
		return Bigger
	case "biohazard", "fae-biohazard":
		return Biohazard
	case "blogger_circle", "fae-blogger_circle":
		return BloggerCircle
	case "blogger_square", "fae-blogger_square":
		return BloggerSquare
	case "bones", "fae-bones":
		return Bones
	case "book_open", "fae-book_open":
		return BookOpen
	case "book_open_o", "fae-book_open_o":
		return BookOpenO
	case "brain", "fae-brain":
		return Brain
	case "bread", "fae-bread":
		return Bread
	case "butterfly", "fae-butterfly":
		return Butterfly
	case "carot", "fae-carot":
		return Carot
	case "cc_by", "fae-cc_by":
		return CcBy
	case "cc_cc", "fae-cc_cc":
		return CcCc
	case "cc_nc", "fae-cc_nc":
		return CcNc
	case "cc_nc_eu", "fae-cc_nc_eu":
		return CcNcEu
	case "cc_nc_jp", "fae-cc_nc_jp":
		return CcNcJp
	case "cc_nd", "fae-cc_nd":
		return CcNd
	case "cc_remix", "fae-cc_remix":
		return CcRemix
	case "cc_sa", "fae-cc_sa":
		return CcSa
	case "cc_share", "fae-cc_share":
		return CcShare
	case "cc_zero", "fae-cc_zero":
		return CcZero
	case "checklist_o", "fae-checklist_o":
		return ChecklistO
	case "cheese", "fae-cheese":
		return Cheese
	case "cherry", "fae-cherry":
		return Cherry
	case "chess_bishop", "fae-chess_bishop":
		return ChessBishop
	case "chess_horse", "fae-chess_horse":
		return ChessHorse
	case "chess_king", "fae-chess_king":
		return ChessKing
	case "chess_pawn", "fae-chess_pawn":
		return ChessPawn
	case "chess_queen", "fae-chess_queen":
		return ChessQueen
	case "chess_tower", "fae-chess_tower":
		return ChessTower
	case "chicken_thigh", "fae-chicken_thigh":
		return ChickenThigh
	case "chilli", "fae-chilli":
		return Chilli
	case "chip", "fae-chip":
		return Chip
	case "cicling", "fae-cicling":
		return Cicling
	case "cloud", "fae-cloud":
		return Cloud
	case "cockroach", "fae-cockroach":
		return Cockroach
	case "coffe_beans", "fae-coffe_beans":
		return CoffeBeans
	case "coins", "fae-coins":
		return Coins
	case "comb", "fae-comb":
		return Comb
	case "comet", "fae-comet":
		return Comet
	case "crown", "fae-crown":
		return Crown
	case "cup_coffe", "fae-cup_coffe":
		return CupCoffe
	case "dice", "fae-dice":
		return Dice
	case "disco", "fae-disco":
		return Disco
	case "dna", "fae-dna":
		return Dna
	case "donut", "fae-donut":
		return Donut
	case "dress", "fae-dress":
		return Dress
	case "drop", "fae-drop":
		return Drop
	case "ello", "fae-ello":
		return Ello
	case "envelope_open", "fae-envelope_open":
		return EnvelopeOpen
	case "envelope_open_o", "fae-envelope_open_o":
		return EnvelopeOpenO
	case "equal", "fae-equal":
		return Equal
	case "equal_bigger", "fae-equal_bigger":
		return EqualBigger
	case "feedly", "fae-feedly":
		return Feedly
	case "file_export", "fae-file_export":
		return FileExport
	case "file_import", "fae-file_import":
		return FileImport
	case "fingerprint", "fae-fingerprint":
		return Fingerprint
	case "floppy", "fae-floppy":
		return Floppy
	case "footprint", "fae-footprint":
		return Footprint
	case "freecodecamp", "fae-freecodecamp":
		return Freecodecamp
	case "galaxy", "fae-galaxy":
		return Galaxy
	case "galery", "fae-galery":
		return Galery
	case "gift_card", "fae-gift_card":
		return GiftCard
	case "glass", "fae-glass":
		return Glass
	case "google_drive", "fae-google_drive":
		return GoogleDrive
	case "google_play", "fae-google_play":
		return GooglePlay
	case "gps", "fae-gps":
		return Gps
	case "grav", "fae-grav":
		return Grav
	case "guitar", "fae-guitar":
		return Guitar
	case "gut", "fae-gut":
		return Gut
	case "halter", "fae-halter":
		return Halter
	case "hamburger", "fae-hamburger":
		return Hamburger
	case "hat", "fae-hat":
		return Hat
	case "hexagon", "fae-hexagon":
		return Hexagon
	case "high_heel", "fae-high_heel":
		return HighHeel
	case "hotdog", "fae-hotdog":
		return Hotdog
	case "ice_cream", "fae-ice_cream":
		return IceCream
	case "id_card", "fae-id_card":
		return IdCard
	case "imdb", "fae-imdb":
		return Imdb
	case "infinity", "fae-infinity":
		return Infinity
	case "injection", "fae-injection":
		return Injection
	case "isle", "fae-isle":
		return Isle
	case "java", "fae-java":
		return Java
	case "layers", "fae-layers":
		return Layers
	case "lips", "fae-lips":
		return Lips
	case "lipstick", "fae-lipstick":
		return Lipstick
	case "liver", "fae-liver":
		return Liver
	case "lollipop", "fae-lollipop":
		return Lollipop
	case "loyalty_card", "fae-loyalty_card":
		return LoyaltyCard
	case "lung", "fae-lung":
		return Lung
	case "makeup_brushes", "fae-makeup_brushes":
		return MakeupBrushes
	case "maximize", "fae-maximize":
		return Maximize
	case "meat", "fae-meat":
		return Meat
	case "medicine", "fae-medicine":
		return Medicine
	case "microscope", "fae-microscope":
		return Microscope
	case "milk_bottle", "fae-milk_bottle":
		return MilkBottle
	case "minimize", "fae-minimize":
		return Minimize
	case "molecule", "fae-molecule":
		return Molecule
	case "moon_cloud", "fae-moon_cloud":
		return MoonCloud
	case "mountains", "fae-mountains":
		return Mountains
	case "mushroom", "fae-mushroom":
		return Mushroom
	case "mustache", "fae-mustache":
		return Mustache
	case "mysql", "fae-mysql":
		return Mysql
	case "nintendo", "fae-nintendo":
		return Nintendo
	case "orange", "fae-orange":
		return Orange
	case "palette_color", "fae-palette_color":
		return PaletteColor
	case "peach", "fae-peach":
		return Peach
	case "pear", "fae-pear":
		return Pear
	case "pi", "fae-pi":
		return Pi
	case "pizza", "fae-pizza":
		return Pizza
	case "planet", "fae-planet":
		return Planet
	case "plant", "fae-plant":
		return Plant
	case "playstation", "fae-playstation":
		return Playstation
	case "poison", "fae-poison":
		return Poison
	case "popcorn", "fae-popcorn":
		return Popcorn
	case "popsicle", "fae-popsicle":
		return Popsicle
	case "pulse", "fae-pulse":
		return Pulse
	case "python", "fae-python":
		return Python
	case "quora_circle", "fae-quora_circle":
		return QuoraCircle
	case "quora_square", "fae-quora_square":
		return QuoraSquare
	case "radioactive", "fae-radioactive":
		return Radioactive
	case "raining", "fae-raining":
		return Raining
	case "real_heart", "fae-real_heart":
		return RealHeart
	case "refrigerator", "fae-refrigerator":
		return Refrigerator
	case "restore", "fae-restore":
		return Restore
	case "ring", "fae-ring":
		return Ring
	case "ruby", "fae-ruby":
		return Ruby
	case "ruby_o", "fae-ruby_o":
		return RubyO
	case "ruler", "fae-ruler":
		return Ruler
	case "shirt", "fae-shirt":
		return Shirt
	case "slash", "fae-slash":
		return Slash
	case "smaller", "fae-smaller":
		return Smaller
	case "snowing", "fae-snowing":
		return Snowing
	case "soda", "fae-soda":
		return Soda
	case "sofa", "fae-sofa":
		return Sofa
	case "soup", "fae-soup":
		return Soup
	case "spermatozoon", "fae-spermatozoon":
		return Spermatozoon
	case "spin_double", "fae-spin_double":
		return SpinDouble
	case "stomach", "fae-stomach":
		return Stomach
	case "storm", "fae-storm":
		return Storm
	case "sun_cloud", "fae-sun_cloud":
		return SunCloud
	case "sushi", "fae-sushi":
		return Sushi
	case "tacos", "fae-tacos":
		return Tacos
	case "telegram", "fae-telegram":
		return Telegram
	case "telegram_circle", "fae-telegram_circle":
		return TelegramCircle
	case "telescope", "fae-telescope":
		return Telescope
	case "thermometer", "fae-thermometer":
		return Thermometer
	case "thermometer_high", "fae-thermometer_high":
		return ThermometerHigh
	case "thermometer_low", "fae-thermometer_low":
		return ThermometerLow
	case "thin_close", "fae-thin_close":
		return ThinClose
	case "toilet", "fae-toilet":
		return Toilet
	case "tools", "fae-tools":
		return Tools
	case "tooth", "fae-tooth":
		return Tooth
	case "tree", "fae-tree":
		return Tree
	case "triangle_ruler", "fae-triangle_ruler":
		return TriangleRuler
	case "umbrella", "fae-umbrella":
		return Umbrella
	case "uterus", "fae-uterus":
		return Uterus
	case "virus", "fae-virus":
		return Virus
	case "w3c", "fae-w3c":
		return W3C
	case "walking", "fae-walking":
		return Walking
	case "wallet", "fae-wallet":
		return Wallet
	case "wind", "fae-wind":
		return Wind
	case "xbox", "fae-xbox":
		return Xbox
	default:
		return nil
	}
}

// AllGlyphIDs returns an iterator over all the IDs of the glyphs in the class.
func AllGlyphIDs() iter.Seq[string] {
	return func(yield func(string) bool) {
		for glyph := range AllGlyphs() {
			if !yield(glyph.ID) {
				return
			}
		}
	}
}

// AllGlyphFullIDs returns an iterator over all the full IDs of the glyphs in the class.
func AllGlyphFullIDs() iter.Seq[string] {
	return func(yield func(string) bool) {
		for glyph := range AllGlyphs() {
			if !yield(glyph.FullID()) {
				return
			}
		}
	}
}
