// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.

package fae

import (
	"iter"
	"maps"
	"strings"

	"github.com/lrstanley/go-nf"
)

var (
	allGlyphs = map[string]nf.Glyph{
		"apple_fruit":      AppleFruit,
		"atom":             Atom,
		"bacteria":         Bacteria,
		"banana":           Banana,
		"bath":             Bath,
		"bed":              Bed,
		"benzene":          Benzene,
		"bigger":           Bigger,
		"biohazard":        Biohazard,
		"blogger_circle":   BloggerCircle,
		"blogger_square":   BloggerSquare,
		"bones":            Bones,
		"book_open":        BookOpen,
		"book_open_o":      BookOpenO,
		"brain":            Brain,
		"bread":            Bread,
		"butterfly":        Butterfly,
		"carot":            Carot,
		"cc_by":            CcBy,
		"cc_cc":            CcCc,
		"cc_nc":            CcNc,
		"cc_nc_eu":         CcNcEu,
		"cc_nc_jp":         CcNcJp,
		"cc_nd":            CcNd,
		"cc_remix":         CcRemix,
		"cc_sa":            CcSa,
		"cc_share":         CcShare,
		"cc_zero":          CcZero,
		"checklist_o":      ChecklistO,
		"cheese":           Cheese,
		"cherry":           Cherry,
		"chess_bishop":     ChessBishop,
		"chess_horse":      ChessHorse,
		"chess_king":       ChessKing,
		"chess_pawn":       ChessPawn,
		"chess_queen":      ChessQueen,
		"chess_tower":      ChessTower,
		"chicken_thigh":    ChickenThigh,
		"chilli":           Chilli,
		"chip":             Chip,
		"cicling":          Cicling,
		"cloud":            Cloud,
		"cockroach":        Cockroach,
		"coffe_beans":      CoffeBeans,
		"coins":            Coins,
		"comb":             Comb,
		"comet":            Comet,
		"crown":            Crown,
		"cup_coffe":        CupCoffe,
		"dice":             Dice,
		"disco":            Disco,
		"dna":              Dna,
		"donut":            Donut,
		"dress":            Dress,
		"drop":             Drop,
		"ello":             Ello,
		"envelope_open":    EnvelopeOpen,
		"envelope_open_o":  EnvelopeOpenO,
		"equal":            Equal,
		"equal_bigger":     EqualBigger,
		"feedly":           Feedly,
		"file_export":      FileExport,
		"file_import":      FileImport,
		"fingerprint":      Fingerprint,
		"floppy":           Floppy,
		"footprint":        Footprint,
		"freecodecamp":     Freecodecamp,
		"galaxy":           Galaxy,
		"galery":           Galery,
		"gift_card":        GiftCard,
		"glass":            Glass,
		"google_drive":     GoogleDrive,
		"google_play":      GooglePlay,
		"gps":              Gps,
		"grav":             Grav,
		"guitar":           Guitar,
		"gut":              Gut,
		"halter":           Halter,
		"hamburger":        Hamburger,
		"hat":              Hat,
		"hexagon":          Hexagon,
		"high_heel":        HighHeel,
		"hotdog":           Hotdog,
		"ice_cream":        IceCream,
		"id_card":          IdCard,
		"imdb":             Imdb,
		"infinity":         Infinity,
		"injection":        Injection,
		"isle":             Isle,
		"java":             Java,
		"layers":           Layers,
		"lips":             Lips,
		"lipstick":         Lipstick,
		"liver":            Liver,
		"lollipop":         Lollipop,
		"loyalty_card":     LoyaltyCard,
		"lung":             Lung,
		"makeup_brushes":   MakeupBrushes,
		"maximize":         Maximize,
		"meat":             Meat,
		"medicine":         Medicine,
		"microscope":       Microscope,
		"milk_bottle":      MilkBottle,
		"minimize":         Minimize,
		"molecule":         Molecule,
		"moon_cloud":       MoonCloud,
		"mountains":        Mountains,
		"mushroom":         Mushroom,
		"mustache":         Mustache,
		"mysql":            Mysql,
		"nintendo":         Nintendo,
		"orange":           Orange,
		"palette_color":    PaletteColor,
		"peach":            Peach,
		"pear":             Pear,
		"pi":               Pi,
		"pizza":            Pizza,
		"planet":           Planet,
		"plant":            Plant,
		"playstation":      Playstation,
		"poison":           Poison,
		"popcorn":          Popcorn,
		"popsicle":         Popsicle,
		"pulse":            Pulse,
		"python":           Python,
		"quora_circle":     QuoraCircle,
		"quora_square":     QuoraSquare,
		"radioactive":      Radioactive,
		"raining":          Raining,
		"real_heart":       RealHeart,
		"refrigerator":     Refrigerator,
		"restore":          Restore,
		"ring":             Ring,
		"ruby":             Ruby,
		"ruby_o":           RubyO,
		"ruler":            Ruler,
		"shirt":            Shirt,
		"slash":            Slash,
		"smaller":          Smaller,
		"snowing":          Snowing,
		"soda":             Soda,
		"sofa":             Sofa,
		"soup":             Soup,
		"spermatozoon":     Spermatozoon,
		"spin_double":      SpinDouble,
		"stomach":          Stomach,
		"storm":            Storm,
		"sun_cloud":        SunCloud,
		"sushi":            Sushi,
		"tacos":            Tacos,
		"telegram":         Telegram,
		"telegram_circle":  TelegramCircle,
		"telescope":        Telescope,
		"thermometer":      Thermometer,
		"thermometer_high": ThermometerHigh,
		"thermometer_low":  ThermometerLow,
		"thin_close":       ThinClose,
		"toilet":           Toilet,
		"tools":            Tools,
		"tooth":            Tooth,
		"tree":             Tree,
		"triangle_ruler":   TriangleRuler,
		"umbrella":         Umbrella,
		"uterus":           Uterus,
		"virus":            Virus,
		"w3c":              W3C,
		"walking":          Walking,
		"wallet":           Wallet,
		"wind":             Wind,
		"xbox":             Xbox,
	}
)

// AllGlyphs returns an iterator over all the glyphs in the fae class,
// returned in no particular order.
func AllGlyphs() iter.Seq[nf.Glyph] {
	return maps.Values(allGlyphs)
}

// ByID finds a glyph by its short or full ID within the class, or an empty string
// if the glyph is not found.
func ByID(id string) nf.Glyph {
	if glyph, ok := allGlyphs[id]; ok {
		return glyph
	}
	if _, stripped, ok := strings.Cut(id, string(Class)+"-"); ok {
		if glyph, gok := allGlyphs[stripped]; gok {
			return glyph
		}
	}
	return ""
}

// AllGlyphIDs returns an iterator over all the IDs of the glyphs in the class,
// returned in no particular order.
func AllGlyphIDs() iter.Seq[string] {
	return maps.Keys(allGlyphs)
}

// AllGlyphFullIDs returns an iterator over all the full IDs of the glyphs in
// the class, returned in no particular order.
func AllGlyphFullIDs() iter.Seq[string] {
	return func(yield func(string) bool) {
		for id := range allGlyphs {
			if !yield(string(Class) + "-" + id) {
				return
			}
		}
	}
}
