// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.
//
// Glyphs are also under various licenses, as documented here:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/LICENSE
//
// Generated using glyph info from:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/glyphnames.json
//
// Additional information:
//  * Website: https://www.nerdfonts.com
//  * Development Website: https://github.com/ryanoasis/nerd-fonts
//  * Version: 3.4.0

// Package pl contains the Nerd Fonts glyphs for the "pl" class.
package pl

import "github.com/lrstanley/go-nf"

const (
	// ClassName is the name of the class.
	ClassName = "pl"

	// Version is the version of the Nerd Fonts project which this package was generated from.
	Version = "3.4.0"
)

// Branch () represents the "pl-branch" glyph.
var Branch = &nf.Glyph{
	ID:      "branch",
	Class:   ClassName,
	Char:    "",
	Unicode: "\ue0a0",
}

// CurrentLine () represents the "pl-current_line" glyph.
var CurrentLine = &nf.Glyph{
	ID:      "current_line",
	Class:   ClassName,
	Char:    "",
	Unicode: "\ue0a1",
}

// Hostname () represents the "pl-hostname" glyph.
var Hostname = &nf.Glyph{
	ID:      "hostname",
	Class:   ClassName,
	Char:    "",
	Unicode: "\ue0a2",
}

// LeftHardDivider () represents the "pl-left_hard_divider" glyph.
var LeftHardDivider = &nf.Glyph{
	ID:      "left_hard_divider",
	Class:   ClassName,
	Char:    "",
	Unicode: "\ue0b0",
}

// LeftSoftDivider () represents the "pl-left_soft_divider" glyph.
var LeftSoftDivider = &nf.Glyph{
	ID:      "left_soft_divider",
	Class:   ClassName,
	Char:    "",
	Unicode: "\ue0b1",
}

// LineNumber () represents the "pl-line_number" glyph.
var LineNumber = &nf.Glyph{
	ID:      "line_number",
	Class:   ClassName,
	Char:    "",
	Unicode: "\ue0a1",
}

// Readonly () represents the "pl-readonly" glyph.
var Readonly = &nf.Glyph{
	ID:      "readonly",
	Class:   ClassName,
	Char:    "",
	Unicode: "\ue0a2",
}

// RightHardDivider () represents the "pl-right_hard_divider" glyph.
var RightHardDivider = &nf.Glyph{
	ID:      "right_hard_divider",
	Class:   ClassName,
	Char:    "",
	Unicode: "\ue0b2",
}

// RightSoftDivider () represents the "pl-right_soft_divider" glyph.
var RightSoftDivider = &nf.Glyph{
	ID:      "right_soft_divider",
	Class:   ClassName,
	Char:    "",
	Unicode: "\ue0b3",
}
