// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.
//
// Glyphs are also under various licenses, as documented here:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/LICENSE
//
// Generated using glyph info from:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/glyphnames.json
//
// Additional information:
//  * Website: https://www.nerdfonts.com
//  * Development Website: https://github.com/ryanoasis/nerd-fonts
//  * Version: 3.4.0

// Package seti contains the Nerd Fonts glyphs for the "seti" class.
package seti

import "github.com/lrstanley/go-nf"

const (
	// Class is the name of the class.
	Class nf.Class = "seti"

	// Version is the version of the Nerd Fonts project which this package was generated from.
	Version = "3.4.0"
)

const (
	Apple             nf.Glyph = "" //  ("\ue635") represents the "seti-apple" glyph.
	Argdown           nf.Glyph = "" //  ("\ue636") represents the "seti-argdown" glyph.
	Asm               nf.Glyph = "" //  ("\ue637") represents the "seti-asm" glyph.
	Audio             nf.Glyph = "" //  ("\ue638") represents the "seti-audio" glyph.
	Babel             nf.Glyph = "" //  ("\ue639") represents the "seti-babel" glyph.
	Bazel             nf.Glyph = "" //  ("\ue63a") represents the "seti-bazel" glyph.
	Bicep             nf.Glyph = "" //  ("\ue63b") represents the "seti-bicep" glyph.
	Bower             nf.Glyph = "" //  ("\ue61a") represents the "seti-bower" glyph.
	Bsl               nf.Glyph = "" //  ("\ue63c") represents the "seti-bsl" glyph.
	C                 nf.Glyph = "" //  ("\ue649") represents the "seti-c" glyph.
	CSharp            nf.Glyph = "" //  ("\ue648") represents the "seti-c_sharp" glyph.
	Cake              nf.Glyph = "" //  ("\ue63e") represents the "seti-cake" glyph.
	CakePhp           nf.Glyph = "" //  ("\ue63d") represents the "seti-cake_php" glyph.
	Checkbox          nf.Glyph = "" //  ("\ue63f") represents the "seti-checkbox" glyph.
	CheckboxUnchecked nf.Glyph = "" //  ("\ue640") represents the "seti-checkbox_unchecked" glyph.
	Cjsx              nf.Glyph = "" //  ("\ue61b") represents the "seti-cjsx" glyph.
	Clock             nf.Glyph = "" //  ("\ue641") represents the "seti-clock" glyph.
	Clojure           nf.Glyph = "" //  ("\ue642") represents the "seti-clojure" glyph.
	CodeClimate       nf.Glyph = "" //  ("\ue643") represents the "seti-code_climate" glyph.
	CodeSearch        nf.Glyph = "" //  ("\ue644") represents the "seti-code_search" glyph.
	Coffee            nf.Glyph = "" //  ("\ue61b") represents the "seti-coffee" glyph.
	Coldfusion        nf.Glyph = "" //  ("\ue645") represents the "seti-coldfusion" glyph.
	Config            nf.Glyph = "" //  ("\ue615") represents the "seti-config" glyph.
	Cpp               nf.Glyph = "" //  ("\ue646") represents the "seti-cpp" glyph.
	Crystal           nf.Glyph = "" //  ("\ue62f") represents the "seti-crystal" glyph.
	CrystalEmbedded   nf.Glyph = "" //  ("\ue647") represents the "seti-crystal_embedded" glyph.
	Css               nf.Glyph = "" //  ("\ue614") represents the "seti-css" glyph.
	Csv               nf.Glyph = "" //  ("\ue64a") represents the "seti-csv" glyph.
	Cu                nf.Glyph = "" //  ("\ue64b") represents the "seti-cu" glyph.
	D                 nf.Glyph = "" //  ("\ue651") represents the "seti-d" glyph.
	Dart              nf.Glyph = "" //  ("\ue64c") represents the "seti-dart" glyph.
	Db                nf.Glyph = "" //  ("\ue64d") represents the "seti-db" glyph.
	Default           nf.Glyph = "" //  ("\ue64e") represents the "seti-default" glyph.
	DeprecationCop    nf.Glyph = "" //  ("\ue64f") represents the "seti-deprecation_cop" glyph.
	Docker            nf.Glyph = "" //  ("\ue650") represents the "seti-docker" glyph.
	Editorconfig      nf.Glyph = "" //  ("\ue652") represents the "seti-editorconfig" glyph.
	Ejs               nf.Glyph = "" //  ("\ue618") represents the "seti-ejs" glyph.
	Elixir            nf.Glyph = "" //  ("\ue62d") represents the "seti-elixir" glyph.
	ElixirScript      nf.Glyph = "" //  ("\ue653") represents the "seti-elixir_script" glyph.
	Elm               nf.Glyph = "" //  ("\ue62c") represents the "seti-elm" glyph.
	Error             nf.Glyph = "" //  ("\ue654") represents the "seti-error" glyph.
	Eslint            nf.Glyph = "" //  ("\ue655") represents the "seti-eslint" glyph.
	Ethereum          nf.Glyph = "" //  ("\ue656") represents the "seti-ethereum" glyph.
	FSharp            nf.Glyph = "" //  ("\ue65a") represents the "seti-f_sharp" glyph.
	Favicon           nf.Glyph = "" //  ("\ue623") represents the "seti-favicon" glyph.
	Firebase          nf.Glyph = "" //  ("\ue657") represents the "seti-firebase" glyph.
	Firefox           nf.Glyph = "" //  ("\ue658") represents the "seti-firefox" glyph.
	Folder            nf.Glyph = "" //  ("\ue613") represents the "seti-folder" glyph.
	Font              nf.Glyph = "" //  ("\ue659") represents the "seti-font" glyph.
	Git               nf.Glyph = "" //  ("\ue65d") represents the "seti-git" glyph.
	GitFolder         nf.Glyph = "" //  ("\ue65d") represents the "seti-git_folder" glyph.
	GitIgnore         nf.Glyph = "" //  ("\ue65d") represents the "seti-git_ignore" glyph.
	Github            nf.Glyph = "" //  ("\ue65b") represents the "seti-github" glyph.
	Gitlab            nf.Glyph = "" //  ("\ue65c") represents the "seti-gitlab" glyph.
	Go                nf.Glyph = "" //  ("\ue627") represents the "seti-go" glyph.
	Go2               nf.Glyph = "" //  ("\ue65e") represents the "seti-go2" glyph.
	Godot             nf.Glyph = "" //  ("\ue65f") represents the "seti-godot" glyph.
	Gradle            nf.Glyph = "" //  ("\ue660") represents the "seti-gradle" glyph.
	Grails            nf.Glyph = "" //  ("\ue661") represents the "seti-grails" glyph.
	Graphql           nf.Glyph = "" //  ("\ue662") represents the "seti-graphql" glyph.
	Grunt             nf.Glyph = "" //  ("\ue611") represents the "seti-grunt" glyph.
	Gulp              nf.Glyph = "" //  ("\ue610") represents the "seti-gulp" glyph.
	Hacklang          nf.Glyph = "" //  ("\ue663") represents the "seti-hacklang" glyph.
	Haml              nf.Glyph = "" //  ("\ue664") represents the "seti-haml" glyph.
	Happenings        nf.Glyph = "" //  ("\ue665") represents the "seti-happenings" glyph.
	Haskell           nf.Glyph = "" //  ("\ue61f") represents the "seti-haskell" glyph.
	Haxe              nf.Glyph = "" //  ("\ue666") represents the "seti-haxe" glyph.
	Heroku            nf.Glyph = "" //  ("\ue607") represents the "seti-heroku" glyph.
	Hex               nf.Glyph = "" //  ("\ue667") represents the "seti-hex" glyph.
	Home              nf.Glyph = "" //  ("\ue617") represents the "seti-home" glyph.
	Html              nf.Glyph = "" //  ("\ue60e") represents the "seti-html" glyph.
	Ignored           nf.Glyph = "" //  ("\ue668") represents the "seti-ignored" glyph.
	Illustrator       nf.Glyph = "" //  ("\ue669") represents the "seti-illustrator" glyph.
	Image             nf.Glyph = "" //  ("\ue60d") represents the "seti-image" glyph.
	Info              nf.Glyph = "" //  ("\ue66a") represents the "seti-info" glyph.
	Ionic             nf.Glyph = "" //  ("\ue66b") represents the "seti-ionic" glyph.
	Jade              nf.Glyph = "" //  ("\ue66c") represents the "seti-jade" glyph.
	Java              nf.Glyph = "" //  ("\ue66d") represents the "seti-java" glyph.
	Javascript        nf.Glyph = "" //  ("\ue60c") represents the "seti-javascript" glyph.
	Jenkins           nf.Glyph = "" //  ("\ue66e") represents the "seti-jenkins" glyph.
	Jinja             nf.Glyph = "" //  ("\ue66f") represents the "seti-jinja" glyph.
	Json              nf.Glyph = "" //  ("\ue60b") represents the "seti-json" glyph.
	Julia             nf.Glyph = "" //  ("\ue624") represents the "seti-julia" glyph.
	Karma             nf.Glyph = "" //  ("\ue622") represents the "seti-karma" glyph.
	Kotlin            nf.Glyph = "" //  ("\ue634") represents the "seti-kotlin" glyph.
	Less              nf.Glyph = "" //  ("\ue60b") represents the "seti-less" glyph.
	License           nf.Glyph = "" //  ("\ue60a") represents the "seti-license" glyph.
	Liquid            nf.Glyph = "" //  ("\ue670") represents the "seti-liquid" glyph.
	Livescript        nf.Glyph = "" //  ("\ue671") represents the "seti-livescript" glyph.
	Lock              nf.Glyph = "" //  ("\ue672") represents the "seti-lock" glyph.
	Lua               nf.Glyph = "" //  ("\ue620") represents the "seti-lua" glyph.
	Makefile          nf.Glyph = "" //  ("\ue673") represents the "seti-makefile" glyph.
	Markdown          nf.Glyph = "" //  ("\ue609") represents the "seti-markdown" glyph.
	Maven             nf.Glyph = "" //  ("\ue674") represents the "seti-maven" glyph.
	Mdo               nf.Glyph = "" //  ("\ue675") represents the "seti-mdo" glyph.
	Mustache          nf.Glyph = "" //  ("\ue60f") represents the "seti-mustache" glyph.
	NewFile           nf.Glyph = "" //  ("\ue676") represents the "seti-new_file" glyph.
	Nim               nf.Glyph = "" //  ("\ue677") represents the "seti-nim" glyph.
	Notebook          nf.Glyph = "" //  ("\ue678") represents the "seti-notebook" glyph.
	Npm               nf.Glyph = "" //  ("\ue616") represents the "seti-npm" glyph.
	NpmIgnored        nf.Glyph = "" //  ("\ue616") represents the "seti-npm_ignored" glyph.
	Nunjucks          nf.Glyph = "" //  ("\ue679") represents the "seti-nunjucks" glyph.
	Ocaml             nf.Glyph = "" //  ("\ue67a") represents the "seti-ocaml" glyph.
	Odata             nf.Glyph = "" //  ("\ue67b") represents the "seti-odata" glyph.
	Pddl              nf.Glyph = "" //  ("\ue67c") represents the "seti-pddl" glyph.
	Pdf               nf.Glyph = "" //  ("\ue67d") represents the "seti-pdf" glyph.
	Perl              nf.Glyph = "" //  ("\ue67e") represents the "seti-perl" glyph.
	Photoshop         nf.Glyph = "" //  ("\ue67f") represents the "seti-photoshop" glyph.
	Php               nf.Glyph = "" //  ("\ue608") represents the "seti-php" glyph.
	Pipeline          nf.Glyph = "" //  ("\ue680") represents the "seti-pipeline" glyph.
	Plan              nf.Glyph = "" //  ("\ue681") represents the "seti-plan" glyph.
	Platformio        nf.Glyph = "" //  ("\ue682") represents the "seti-platformio" glyph.
	PlayArrow         nf.Glyph = "" //  ("\ue602") represents the "seti-play_arrow" glyph.
	Powershell        nf.Glyph = "" //  ("\ue683") represents the "seti-powershell" glyph.
	Prisma            nf.Glyph = "" //  ("\ue684") represents the "seti-prisma" glyph.
	Project           nf.Glyph = "" //  ("\ue601") represents the "seti-project" glyph.
	Prolog            nf.Glyph = "" //  ("\ue685") represents the "seti-prolog" glyph.
	Pug               nf.Glyph = "" //  ("\ue686") represents the "seti-pug" glyph.
	Puppet            nf.Glyph = "" //  ("\ue631") represents the "seti-puppet" glyph.
	Purescript        nf.Glyph = "" //  ("\ue630") represents the "seti-purescript" glyph.
	Python            nf.Glyph = "" //  ("\ue606") represents the "seti-python" glyph.
	R                 nf.Glyph = "" //  ("\ue68a") represents the "seti-r" glyph.
	Rails             nf.Glyph = "" //  ("\ue604") represents the "seti-rails" glyph.
	React             nf.Glyph = "" //  ("\ue625") represents the "seti-react" glyph.
	Reasonml          nf.Glyph = "" //  ("\ue687") represents the "seti-reasonml" glyph.
	Rescript          nf.Glyph = "" //  ("\ue688") represents the "seti-rescript" glyph.
	Rollup            nf.Glyph = "" //  ("\ue689") represents the "seti-rollup" glyph.
	Ruby              nf.Glyph = "" //  ("\ue605") represents the "seti-ruby" glyph.
	Rust              nf.Glyph = "" //  ("\ue68b") represents the "seti-rust" glyph.
	Salesforce        nf.Glyph = "" //  ("\ue68c") represents the "seti-salesforce" glyph.
	Sass              nf.Glyph = "" //  ("\ue603") represents the "seti-sass" glyph.
	Sbt               nf.Glyph = "" //  ("\ue68d") represents the "seti-sbt" glyph.
	Scala             nf.Glyph = "" //  ("\ue68e") represents the "seti-scala" glyph.
	Search            nf.Glyph = "" //  ("\ue68f") represents the "seti-search" glyph.
	Settings          nf.Glyph = "" //  ("\ue690") represents the "seti-settings" glyph.
	Shell             nf.Glyph = "" //  ("\ue691") represents the "seti-shell" glyph.
	Slim              nf.Glyph = "" //  ("\ue692") represents the "seti-slim" glyph.
	Smarty            nf.Glyph = "" //  ("\ue693") represents the "seti-smarty" glyph.
	Spring            nf.Glyph = "" //  ("\ue694") represents the "seti-spring" glyph.
	Stylelint         nf.Glyph = "" //  ("\ue695") represents the "seti-stylelint" glyph.
	Stylus            nf.Glyph = "" //  ("\ue600") represents the "seti-stylus" glyph.
	Sublime           nf.Glyph = "" //  ("\ue696") represents the "seti-sublime" glyph.
	Svelte            nf.Glyph = "" //  ("\ue697") represents the "seti-svelte" glyph.
	Svg               nf.Glyph = "" //  ("\ue698") represents the "seti-svg" glyph.
	Swift             nf.Glyph = "" //  ("\ue699") represents the "seti-swift" glyph.
	Terraform         nf.Glyph = "" //  ("\ue69a") represents the "seti-terraform" glyph.
	Tex               nf.Glyph = "" //  ("\ue69b") represents the "seti-tex" glyph.
	Text              nf.Glyph = "" //  ("\ue64e") represents the "seti-text" glyph.
	TimeCop           nf.Glyph = "" //  ("\ue641") represents the "seti-time_cop" glyph.
	Todo              nf.Glyph = "" //  ("\ue69c") represents the "seti-todo" glyph.
	Tsconfig          nf.Glyph = "" //  ("\ue69d") represents the "seti-tsconfig" glyph.
	Twig              nf.Glyph = "" //  ("\ue61c") represents the "seti-twig" glyph.
	Typescript        nf.Glyph = "" //  ("\ue628") represents the "seti-typescript" glyph.
	Vala              nf.Glyph = "" //  ("\ue69e") represents the "seti-vala" glyph.
	Video             nf.Glyph = "" //  ("\ue69f") represents the "seti-video" glyph.
	Vue               nf.Glyph = "" //  ("\ue6a0") represents the "seti-vue" glyph.
	Wasm              nf.Glyph = "" //  ("\ue6a1") represents the "seti-wasm" glyph.
	Wat               nf.Glyph = "" //  ("\ue6a2") represents the "seti-wat" glyph.
	Webpack           nf.Glyph = "" //  ("\ue6a3") represents the "seti-webpack" glyph.
	Wgt               nf.Glyph = "" //  ("\ue6a4") represents the "seti-wgt" glyph.
	Word              nf.Glyph = "" //  ("\ue6a5") represents the "seti-word" glyph.
	Xls               nf.Glyph = "" //  ("\ue6a6") represents the "seti-xls" glyph.
	Xml               nf.Glyph = "" //  ("\ue619") represents the "seti-xml" glyph.
	Yarn              nf.Glyph = "" //  ("\ue6a7") represents the "seti-yarn" glyph.
	Yml               nf.Glyph = "" //  ("\ue6a8") represents the "seti-yml" glyph.
	Zig               nf.Glyph = "" //  ("\ue6a9") represents the "seti-zig" glyph.
	Zip               nf.Glyph = "" //  ("\ue6aa") represents the "seti-zip" glyph.
)
