// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.

package seti

import (
	"iter"
	"maps"
	"strings"

	"github.com/lrstanley/go-nf"
)

var (
	allGlyphs = map[string]nf.Glyph{
		"apple":              Apple,
		"argdown":            Argdown,
		"asm":                Asm,
		"audio":              Audio,
		"babel":              Babel,
		"bazel":              Bazel,
		"bicep":              Bicep,
		"bower":              Bower,
		"bsl":                Bsl,
		"c":                  C,
		"c_sharp":            CSharp,
		"cake":               Cake,
		"cake_php":           CakePhp,
		"checkbox":           Checkbox,
		"checkbox_unchecked": CheckboxUnchecked,
		"cjsx":               Cjsx,
		"clock":              Clock,
		"clojure":            Clojure,
		"code_climate":       CodeClimate,
		"code_search":        CodeSearch,
		"coffee":             Coffee,
		"coldfusion":         Coldfusion,
		"config":             Config,
		"cpp":                Cpp,
		"crystal":            Crystal,
		"crystal_embedded":   CrystalEmbedded,
		"css":                Css,
		"csv":                Csv,
		"cu":                 Cu,
		"d":                  D,
		"dart":               Dart,
		"db":                 Db,
		"default":            Default,
		"deprecation_cop":    DeprecationCop,
		"docker":             Docker,
		"editorconfig":       Editorconfig,
		"ejs":                Ejs,
		"elixir":             Elixir,
		"elixir_script":      ElixirScript,
		"elm":                Elm,
		"error":              Error,
		"eslint":             Eslint,
		"ethereum":           Ethereum,
		"f_sharp":            FSharp,
		"favicon":            Favicon,
		"firebase":           Firebase,
		"firefox":            Firefox,
		"folder":             Folder,
		"font":               Font,
		"git":                Git,
		"git_folder":         GitFolder,
		"git_ignore":         GitIgnore,
		"github":             Github,
		"gitlab":             Gitlab,
		"go":                 Go,
		"go2":                Go2,
		"godot":              Godot,
		"gradle":             Gradle,
		"grails":             Grails,
		"graphql":            Graphql,
		"grunt":              Grunt,
		"gulp":               Gulp,
		"hacklang":           Hacklang,
		"haml":               Haml,
		"happenings":         Happenings,
		"haskell":            Haskell,
		"haxe":               Haxe,
		"heroku":             Heroku,
		"hex":                Hex,
		"home":               Home,
		"html":               Html,
		"ignored":            Ignored,
		"illustrator":        Illustrator,
		"image":              Image,
		"info":               Info,
		"ionic":              Ionic,
		"jade":               Jade,
		"java":               Java,
		"javascript":         Javascript,
		"jenkins":            Jenkins,
		"jinja":              Jinja,
		"json":               Json,
		"julia":              Julia,
		"karma":              Karma,
		"kotlin":             Kotlin,
		"less":               Less,
		"license":            License,
		"liquid":             Liquid,
		"livescript":         Livescript,
		"lock":               Lock,
		"lua":                Lua,
		"makefile":           Makefile,
		"markdown":           Markdown,
		"maven":              Maven,
		"mdo":                Mdo,
		"mustache":           Mustache,
		"new_file":           NewFile,
		"nim":                Nim,
		"notebook":           Notebook,
		"npm":                Npm,
		"npm_ignored":        NpmIgnored,
		"nunjucks":           Nunjucks,
		"ocaml":              Ocaml,
		"odata":              Odata,
		"pddl":               Pddl,
		"pdf":                Pdf,
		"perl":               Perl,
		"photoshop":          Photoshop,
		"php":                Php,
		"pipeline":           Pipeline,
		"plan":               Plan,
		"platformio":         Platformio,
		"play_arrow":         PlayArrow,
		"powershell":         Powershell,
		"prisma":             Prisma,
		"project":            Project,
		"prolog":             Prolog,
		"pug":                Pug,
		"puppet":             Puppet,
		"purescript":         Purescript,
		"python":             Python,
		"r":                  R,
		"rails":              Rails,
		"react":              React,
		"reasonml":           Reasonml,
		"rescript":           Rescript,
		"rollup":             Rollup,
		"ruby":               Ruby,
		"rust":               Rust,
		"salesforce":         Salesforce,
		"sass":               Sass,
		"sbt":                Sbt,
		"scala":              Scala,
		"search":             Search,
		"settings":           Settings,
		"shell":              Shell,
		"slim":               Slim,
		"smarty":             Smarty,
		"spring":             Spring,
		"stylelint":          Stylelint,
		"stylus":             Stylus,
		"sublime":            Sublime,
		"svelte":             Svelte,
		"svg":                Svg,
		"swift":              Swift,
		"terraform":          Terraform,
		"tex":                Tex,
		"text":               Text,
		"time_cop":           TimeCop,
		"todo":               Todo,
		"tsconfig":           Tsconfig,
		"twig":               Twig,
		"typescript":         Typescript,
		"vala":               Vala,
		"video":              Video,
		"vue":                Vue,
		"wasm":               Wasm,
		"wat":                Wat,
		"webpack":            Webpack,
		"wgt":                Wgt,
		"word":               Word,
		"xls":                Xls,
		"xml":                Xml,
		"yarn":               Yarn,
		"yml":                Yml,
		"zig":                Zig,
		"zip":                Zip,
	}
)

// AllGlyphs returns an iterator over all the glyphs in the seti class,
// returned in no particular order.
func AllGlyphs() iter.Seq[nf.Glyph] {
	return maps.Values(allGlyphs)
}

// ByID finds a glyph by its short or full ID within the class, or an empty string
// if the glyph is not found.
func ByID(id string) nf.Glyph {
	if glyph, ok := allGlyphs[id]; ok {
		return glyph
	}
	if _, stripped, ok := strings.Cut(id, string(Class)+"-"); ok {
		if glyph, gok := allGlyphs[stripped]; gok {
			return glyph
		}
	}
	return ""
}

// AllGlyphIDs returns an iterator over all the IDs of the glyphs in the class,
// returned in no particular order.
func AllGlyphIDs() iter.Seq[string] {
	return maps.Keys(allGlyphs)
}

// AllGlyphFullIDs returns an iterator over all the full IDs of the glyphs in
// the class, returned in no particular order.
func AllGlyphFullIDs() iter.Seq[string] {
	return func(yield func(string) bool) {
		for id := range allGlyphs {
			if !yield(string(Class) + "-" + id) {
				return
			}
		}
	}
}
