// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.
//
// Glyphs are also under various licenses, as documented here:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/LICENSE
//
// Generated using glyph info from:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/glyphnames.json
//
// Additional information:
//  * Website: https://www.nerdfonts.com
//  * Development Website: https://github.com/ryanoasis/nerd-fonts
//  * Version: 3.4.0

// Package pom contains the Nerd Fonts glyphs for the "pom" class.
package pom

import "github.com/lrstanley/go-nf"

const (
	// Class is the name of the class.
	Class nf.Class = "pom"

	// Version is the version of the Nerd Fonts project which this package was generated from.
	Version = "3.4.0"
)

const (
	Away                 nf.Glyph = "" //  ("\ue007") represents the "pom-away" glyph.
	CleanCode            nf.Glyph = "" //  ("\ue000") represents the "pom-clean_code" glyph.
	ExternalInterruption nf.Glyph = "" //  ("\ue00a") represents the "pom-external_interruption" glyph.
	InternalInterruption nf.Glyph = "" //  ("\ue009") represents the "pom-internal_interruption" glyph.
	LongPause            nf.Glyph = "" //  ("\ue006") represents the "pom-long_pause" glyph.
	PairProgramming      nf.Glyph = "" //  ("\ue008") represents the "pom-pair_programming" glyph.
	PomodoroDone         nf.Glyph = "" //  ("\ue001") represents the "pom-pomodoro_done" glyph.
	PomodoroEstimated    nf.Glyph = "" //  ("\ue002") represents the "pom-pomodoro_estimated" glyph.
	PomodoroSquashed     nf.Glyph = "" //  ("\ue004") represents the "pom-pomodoro_squashed" glyph.
	PomodoroTicking      nf.Glyph = "" //  ("\ue003") represents the "pom-pomodoro_ticking" glyph.
	ShortPause           nf.Glyph = "" //  ("\ue005") represents the "pom-short_pause" glyph.
)
