// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.

package pom

import (
	"iter"
	"slices"

	"github.com/lrstanley/go-nf"
)

var allGlyphs = []*nf.Glyph{
	Away,
	CleanCode,
	ExternalInterruption,
	InternalInterruption,
	LongPause,
	PairProgramming,
	PomodoroDone,
	PomodoroEstimated,
	PomodoroSquashed,
	PomodoroTicking,
	ShortPause,
}

// AllGlyphs returns an iterator over all the glyphs in the pom class.
func AllGlyphs() iter.Seq[*nf.Glyph] {
	return slices.Values(allGlyphs)
}

// ByID finds a glyph by its ID within the class.
func ByID(id string) *nf.Glyph {
	switch id {
	case "away", "pom-away":
		return Away
	case "clean_code", "pom-clean_code":
		return CleanCode
	case "external_interruption", "pom-external_interruption":
		return ExternalInterruption
	case "internal_interruption", "pom-internal_interruption":
		return InternalInterruption
	case "long_pause", "pom-long_pause":
		return LongPause
	case "pair_programming", "pom-pair_programming":
		return PairProgramming
	case "pomodoro_done", "pom-pomodoro_done":
		return PomodoroDone
	case "pomodoro_estimated", "pom-pomodoro_estimated":
		return PomodoroEstimated
	case "pomodoro_squashed", "pom-pomodoro_squashed":
		return PomodoroSquashed
	case "pomodoro_ticking", "pom-pomodoro_ticking":
		return PomodoroTicking
	case "short_pause", "pom-short_pause":
		return ShortPause
	default:
		return nil
	}
}

// AllGlyphIDs returns an iterator over all the IDs of the glyphs in the class.
func AllGlyphIDs() iter.Seq[string] {
	return func(yield func(string) bool) {
		for glyph := range AllGlyphs() {
			if !yield(glyph.ID) {
				return
			}
		}
	}
}

// AllGlyphFullIDs returns an iterator over all the full IDs of the glyphs in the class.
func AllGlyphFullIDs() iter.Seq[string] {
	return func(yield func(string) bool) {
		for glyph := range AllGlyphs() {
			if !yield(glyph.FullID()) {
				return
			}
		}
	}
}
