// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.

package dev

import (
	"iter"
	"slices"

	"github.com/lrstanley/go-nf"
)

var allGlyphs = []*nf.Glyph{
	Aarch64,
	Adonisjs,
	Aftereffects,
	Akka,
	Algolia,
	Alpinejs,
	Amazonwebservices,
	Anaconda,
	Android,
	Androidstudio,
	Angular,
	Angularjs,
	Angularmaterial,
	Ansible,
	Antdesign,
	Apache,
	Apacheairflow,
	Apachekafka,
	Apachespark,
	Apl,
	Appcelerator,
	Apple,
	Appwrite,
	Archlinux,
	Arduino,
	Argocd,
	Astro,
	Atom,
	Awk,
	Aws,
	Axios,
	Azure,
	Azuredevops,
	Azuresqldatabase,
	Babel,
	Backbone,
	Backbonejs,
	Ballerina,
	Bamboo,
	Bash,
	Beats,
	Behance,
	Bitbucket,
	Blazor,
	Blender,
	Bootstrap,
	Bower,
	Browserstack,
	Bulma,
	Bun,
	C,
	CLang,
	Cairo,
	Cakephp,
	Canva,
	Capacitor,
	Carbon,
	Cassandra,
	Centos,
	Ceylon,
	Chrome,
	Circleci,
	Clarity,
	Clion,
	Clojure,
	ClojureAlt,
	Clojurescript,
	Cloudflare,
	Cloudflareworkers,
	Cmake,
	Codeac,
	Codecov,
	Codeigniter,
	Codepen,
	Coffeescript,
	Composer,
	Confluence,
	Consul,
	Contao,
	Corejs,
	Cosmosdb,
	Couchbase,
	Couchdb,
	Cplusplus,
	Crystal,
	Csharp,
	Css3,
	Css3Full,
	Cucumber,
	Cypressio,
	D3Js,
	Dart,
	Database,
	Datagrip,
	Dataspell,
	Dbeaver,
	Debian,
	Denojs,
	Devicon,
	DigitalOcean,
	Digitalocean,
	Discordjs,
	Django,
	Djangorest,
	Dlang,
	Docker,
	Doctrine,
	Dotnet,
	Dotnetcore,
	Dreamweaver,
	Dropbox,
	Dropwizard,
	Drupal,
	Dynamodb,
	Eclipse,
	Ecto,
	Elasticsearch,
	Electron,
	Eleventy,
	Elixir,
	Elm,
	Emacs,
	Embeddedc,
	Ember,
	Envoy,
	Erlang,
	Eslint,
	Express,
	Facebook,
	Fastapi,
	Fastify,
	Faunadb,
	Feathersjs,
	Fedora,
	Figma,
	Filezilla,
	Firebase,
	Firefox,
	Flask,
	Flutter,
	Fortran,
	Foundation,
	Framermotion,
	Framework7,
	Fsharp,
	Gatling,
	Gatsby,
	Gazebo,
	Gcc,
	Gentoo,
	Ghost,
	GhostSmall,
	Gimp,
	Git,
	GitBranch,
	GitCommit,
	GitCompare,
	GitMerge,
	GitPullRequest,
	Gitbook,
	Github,
	GithubBadge,
	GithubFull,
	Githubactions,
	Githubcodespaces,
	Gitlab,
	Gitpod,
	Gitter,
	Gnu,
	Go,
	Godot,
	Goland,
	Google,
	Googlecloud,
	Gradle,
	Grafana,
	Grails,
	Graphql,
	Groovy,
	Grpc,
	Grunt,
	Gulp,
	Hadoop,
	Handlebars,
	Hardhat,
	Harvester,
	Haskell,
	Haxe,
	Helm,
	Heroku,
	Hibernate,
	Homebrew,
	Html5,
	Hugo,
	Ie,
	Ifttt,
	Illustrator,
	Influxdb,
	Inkscape,
	Insomnia,
	Intellij,
	Ionic,
	Jaegertracing,
	Jamstack,
	Jasmine,
	Java,
	Javascript,
	JavascriptAlt,
	JavascriptBadge,
	Jeet,
	Jekyll,
	JekyllSmall,
	Jenkins,
	Jest,
	Jetbrains,
	Jetpackcompose,
	Jira,
	Jiraalign,
	Jquery,
	Json,
	Jule,
	Julia,
	Junit,
	Jupyter,
	K3Os,
	K3S,
	K6,
	Kaggle,
	Karatelabs,
	Karma,
	Kdeneon,
	Keras,
	Kibana,
	Knexjs,
	Knockout,
	Kotlin,
	Krakenjs,
	KrakenjsBadge,
	Ktor,
	Kubernetes,
	Labview,
	Laravel,
	Latex,
	Less,
	Linkedin,
	Linux,
	Liquibase,
	Livewire,
	Llvm,
	Lodash,
	Logstash,
	Lua,
	Lumen,
	Magento,
	Mariadb,
	Markdown,
	Materializecss,
	Materialui,
	Matlab,
	Matplotlib,
	Maven,
	Maya,
	Meteor,
	Meteorfull,
	Microsoftsqlserver,
	Minitab,
	Mithril,
	Mobx,
	Mocha,
	Modx,
	Moleculer,
	Mongodb,
	Mongoose,
	Moodle,
	MootoolsBadge,
	Mozilla,
	Msdos,
	Mysql,
	Nano,
	Neo4J,
	Neovim,
	Nestjs,
	Netlify,
	Networkx,
	Nextjs,
	Nginx,
	Ngrx,
	Nhibernate,
	Nim,
	Nimble,
	Nixos,
	Nodejs,
	NodejsSmall,
	Nodemon,
	Nodewebkit,
	Nomad,
	Norg,
	Notion,
	Npm,
	Nuget,
	Numpy,
	Nuxtjs,
	Oauth,
	Objectivec,
	Ocaml,
	Ohmyzsh,
	Okta,
	Openal,
	Openapi,
	Opencl,
	Opencv,
	Opengl,
	Openstack,
	Opensuse,
	Opentelemetry,
	Opera,
	Oracle,
	Ory,
	P5Js,
	Packer,
	Pandas,
	Perl,
	Pfsense,
	Phalcon,
	Phoenix,
	Photonengine,
	Photoshop,
	Php,
	Phpstorm,
	Playwright,
	Plotly,
	Pnpm,
	Podman,
	Poetry,
	Polygon,
	Portainer,
	Postcss,
	Postgresql,
	Postman,
	Powershell,
	Premierepro,
	Prisma,
	Processing,
	Prolog,
	Prometheus,
	Protractor,
	Pulsar,
	Pulumi,
	Puppeteer,
	Purescript,
	Putty,
	Pycharm,
	Pypi,
	Pyscript,
	Pytest,
	Python,
	Pytorch,
	Qodana,
	Qt,
	Quarkus,
	Quasar,
	Qwik,
	R,
	Rabbitmq,
	Rails,
	Railway,
	Rancher,
	RaspberryPi,
	Reach,
	React,
	Reactbootstrap,
	Reactnavigation,
	Reactrouter,
	Readthedocs,
	Realm,
	Rect,
	Redhat,
	Redis,
	Redux,
	Renpy,
	Replit,
	Requirejs,
	Rider,
	Rocksdb,
	Rockylinux,
	Rollup,
	Ros,
	Rspec,
	Rstudio,
	Ruby,
	RubyOnRails,
	RubyRough,
	Rubymine,
	Rust,
	Rxjs,
	Safari,
	Salesforce,
	Sanity,
	Sass,
	Scala,
	Scalingo,
	Scikitlearn,
	Sdl,
	Selenium,
	Sema,
	Sentry,
	Sequelize,
	Shopware,
	Shotgrid,
	Sketch,
	Slack,
	SmashingMagazine,
	Socketio,
	Solidity,
	Solidjs,
	Sonarqube,
	Sourcetree,
	Spack,
	Splunk,
	Spring,
	Spss,
	Spyder,
	Sqlalchemy,
	Sqldeveloper,
	Sqlite,
	Ssh,
	Stackoverflow,
	Stata,
	Storybook,
	Streamlit,
	Stylus,
	Sublime,
	Subversion,
	Supabase,
	Svelte,
	Swagger,
	Swift,
	Swiper,
	Symfony,
	SymfonyBadge,
	Tailwindcss,
	Tauri,
	Tensorflow,
	Terminal,
	Terraform,
	Tex,
	Thealgorithms,
	Threedsmax,
	Threejs,
	Titaniumsdk,
	Tomcat,
	Tortoisegit,
	Towergit,
	Traefikmesh,
	Traefikproxy,
	Travis,
	Trello,
	Trpc,
	Twitter,
	Typescript,
	Typo3,
	Ubuntu,
	Uml,
	Unifiedmodelinglanguage,
	Unity,
	UnitySmall,
	Unix,
	Unrealengine,
	Uwsgi,
	V8,
	Vagrant,
	Vala,
	Vault,
	Vercel,
	Vertx,
	Vim,
	Visualbasic,
	Visualstudio,
	Vite,
	Vitejs,
	Vitess,
	Vitest,
	Vscode,
	Vsphere,
	Vuejs,
	Vuestorefront,
	Vuetify,
	Vyper,
	Wasm,
	Webflow,
	Weblate,
	Webpack,
	Webstorm,
	Windows,
	Windows11,
	Woocommerce,
	Wordpress,
	Xamarin,
	Xcode,
	Xd,
	Xml,
	Yaml,
	Yarn,
	Yii,
	Yugabytedb,
	Yunohost,
	Zend,
	Zig,
}

// AllGlyphs returns an iterator over all the glyphs in the dev class.
func AllGlyphs() iter.Seq[*nf.Glyph] {
	return slices.Values(allGlyphs)
}

// ByID finds a glyph by its ID within the class.
func ByID(id string) *nf.Glyph {
	switch id {
	case "aarch64", "dev-aarch64":
		return Aarch64
	case "adonisjs", "dev-adonisjs":
		return Adonisjs
	case "aftereffects", "dev-aftereffects":
		return Aftereffects
	case "akka", "dev-akka":
		return Akka
	case "algolia", "dev-algolia":
		return Algolia
	case "alpinejs", "dev-alpinejs":
		return Alpinejs
	case "amazonwebservices", "dev-amazonwebservices":
		return Amazonwebservices
	case "anaconda", "dev-anaconda":
		return Anaconda
	case "android", "dev-android":
		return Android
	case "androidstudio", "dev-androidstudio":
		return Androidstudio
	case "angular", "dev-angular":
		return Angular
	case "angularjs", "dev-angularjs":
		return Angularjs
	case "angularmaterial", "dev-angularmaterial":
		return Angularmaterial
	case "ansible", "dev-ansible":
		return Ansible
	case "antdesign", "dev-antdesign":
		return Antdesign
	case "apache", "dev-apache":
		return Apache
	case "apacheairflow", "dev-apacheairflow":
		return Apacheairflow
	case "apachekafka", "dev-apachekafka":
		return Apachekafka
	case "apachespark", "dev-apachespark":
		return Apachespark
	case "apl", "dev-apl":
		return Apl
	case "appcelerator", "dev-appcelerator":
		return Appcelerator
	case "apple", "dev-apple":
		return Apple
	case "appwrite", "dev-appwrite":
		return Appwrite
	case "archlinux", "dev-archlinux":
		return Archlinux
	case "arduino", "dev-arduino":
		return Arduino
	case "argocd", "dev-argocd":
		return Argocd
	case "astro", "dev-astro":
		return Astro
	case "atom", "dev-atom":
		return Atom
	case "awk", "dev-awk":
		return Awk
	case "aws", "dev-aws":
		return Aws
	case "axios", "dev-axios":
		return Axios
	case "azure", "dev-azure":
		return Azure
	case "azuredevops", "dev-azuredevops":
		return Azuredevops
	case "azuresqldatabase", "dev-azuresqldatabase":
		return Azuresqldatabase
	case "babel", "dev-babel":
		return Babel
	case "backbone", "dev-backbone":
		return Backbone
	case "backbonejs", "dev-backbonejs":
		return Backbonejs
	case "ballerina", "dev-ballerina":
		return Ballerina
	case "bamboo", "dev-bamboo":
		return Bamboo
	case "bash", "dev-bash":
		return Bash
	case "beats", "dev-beats":
		return Beats
	case "behance", "dev-behance":
		return Behance
	case "bitbucket", "dev-bitbucket":
		return Bitbucket
	case "blazor", "dev-blazor":
		return Blazor
	case "blender", "dev-blender":
		return Blender
	case "bootstrap", "dev-bootstrap":
		return Bootstrap
	case "bower", "dev-bower":
		return Bower
	case "browserstack", "dev-browserstack":
		return Browserstack
	case "bulma", "dev-bulma":
		return Bulma
	case "bun", "dev-bun":
		return Bun
	case "c", "dev-c":
		return C
	case "c_lang", "dev-c_lang":
		return CLang
	case "cairo", "dev-cairo":
		return Cairo
	case "cakephp", "dev-cakephp":
		return Cakephp
	case "canva", "dev-canva":
		return Canva
	case "capacitor", "dev-capacitor":
		return Capacitor
	case "carbon", "dev-carbon":
		return Carbon
	case "cassandra", "dev-cassandra":
		return Cassandra
	case "centos", "dev-centos":
		return Centos
	case "ceylon", "dev-ceylon":
		return Ceylon
	case "chrome", "dev-chrome":
		return Chrome
	case "circleci", "dev-circleci":
		return Circleci
	case "clarity", "dev-clarity":
		return Clarity
	case "clion", "dev-clion":
		return Clion
	case "clojure", "dev-clojure":
		return Clojure
	case "clojure_alt", "dev-clojure_alt":
		return ClojureAlt
	case "clojurescript", "dev-clojurescript":
		return Clojurescript
	case "cloudflare", "dev-cloudflare":
		return Cloudflare
	case "cloudflareworkers", "dev-cloudflareworkers":
		return Cloudflareworkers
	case "cmake", "dev-cmake":
		return Cmake
	case "codeac", "dev-codeac":
		return Codeac
	case "codecov", "dev-codecov":
		return Codecov
	case "codeigniter", "dev-codeigniter":
		return Codeigniter
	case "codepen", "dev-codepen":
		return Codepen
	case "coffeescript", "dev-coffeescript":
		return Coffeescript
	case "composer", "dev-composer":
		return Composer
	case "confluence", "dev-confluence":
		return Confluence
	case "consul", "dev-consul":
		return Consul
	case "contao", "dev-contao":
		return Contao
	case "corejs", "dev-corejs":
		return Corejs
	case "cosmosdb", "dev-cosmosdb":
		return Cosmosdb
	case "couchbase", "dev-couchbase":
		return Couchbase
	case "couchdb", "dev-couchdb":
		return Couchdb
	case "cplusplus", "dev-cplusplus":
		return Cplusplus
	case "crystal", "dev-crystal":
		return Crystal
	case "csharp", "dev-csharp":
		return Csharp
	case "css3", "dev-css3":
		return Css3
	case "css3_full", "dev-css3_full":
		return Css3Full
	case "cucumber", "dev-cucumber":
		return Cucumber
	case "cypressio", "dev-cypressio":
		return Cypressio
	case "d3js", "dev-d3js":
		return D3Js
	case "dart", "dev-dart":
		return Dart
	case "database", "dev-database":
		return Database
	case "datagrip", "dev-datagrip":
		return Datagrip
	case "dataspell", "dev-dataspell":
		return Dataspell
	case "dbeaver", "dev-dbeaver":
		return Dbeaver
	case "debian", "dev-debian":
		return Debian
	case "denojs", "dev-denojs":
		return Denojs
	case "devicon", "dev-devicon":
		return Devicon
	case "digital_ocean", "dev-digital_ocean":
		return DigitalOcean
	case "digitalocean", "dev-digitalocean":
		return Digitalocean
	case "discordjs", "dev-discordjs":
		return Discordjs
	case "django", "dev-django":
		return Django
	case "djangorest", "dev-djangorest":
		return Djangorest
	case "dlang", "dev-dlang":
		return Dlang
	case "docker", "dev-docker":
		return Docker
	case "doctrine", "dev-doctrine":
		return Doctrine
	case "dotnet", "dev-dotnet":
		return Dotnet
	case "dotnetcore", "dev-dotnetcore":
		return Dotnetcore
	case "dreamweaver", "dev-dreamweaver":
		return Dreamweaver
	case "dropbox", "dev-dropbox":
		return Dropbox
	case "dropwizard", "dev-dropwizard":
		return Dropwizard
	case "drupal", "dev-drupal":
		return Drupal
	case "dynamodb", "dev-dynamodb":
		return Dynamodb
	case "eclipse", "dev-eclipse":
		return Eclipse
	case "ecto", "dev-ecto":
		return Ecto
	case "elasticsearch", "dev-elasticsearch":
		return Elasticsearch
	case "electron", "dev-electron":
		return Electron
	case "eleventy", "dev-eleventy":
		return Eleventy
	case "elixir", "dev-elixir":
		return Elixir
	case "elm", "dev-elm":
		return Elm
	case "emacs", "dev-emacs":
		return Emacs
	case "embeddedc", "dev-embeddedc":
		return Embeddedc
	case "ember", "dev-ember":
		return Ember
	case "envoy", "dev-envoy":
		return Envoy
	case "erlang", "dev-erlang":
		return Erlang
	case "eslint", "dev-eslint":
		return Eslint
	case "express", "dev-express":
		return Express
	case "facebook", "dev-facebook":
		return Facebook
	case "fastapi", "dev-fastapi":
		return Fastapi
	case "fastify", "dev-fastify":
		return Fastify
	case "faunadb", "dev-faunadb":
		return Faunadb
	case "feathersjs", "dev-feathersjs":
		return Feathersjs
	case "fedora", "dev-fedora":
		return Fedora
	case "figma", "dev-figma":
		return Figma
	case "filezilla", "dev-filezilla":
		return Filezilla
	case "firebase", "dev-firebase":
		return Firebase
	case "firefox", "dev-firefox":
		return Firefox
	case "flask", "dev-flask":
		return Flask
	case "flutter", "dev-flutter":
		return Flutter
	case "fortran", "dev-fortran":
		return Fortran
	case "foundation", "dev-foundation":
		return Foundation
	case "framermotion", "dev-framermotion":
		return Framermotion
	case "framework7", "dev-framework7":
		return Framework7
	case "fsharp", "dev-fsharp":
		return Fsharp
	case "gatling", "dev-gatling":
		return Gatling
	case "gatsby", "dev-gatsby":
		return Gatsby
	case "gazebo", "dev-gazebo":
		return Gazebo
	case "gcc", "dev-gcc":
		return Gcc
	case "gentoo", "dev-gentoo":
		return Gentoo
	case "ghost", "dev-ghost":
		return Ghost
	case "ghost_small", "dev-ghost_small":
		return GhostSmall
	case "gimp", "dev-gimp":
		return Gimp
	case "git", "dev-git":
		return Git
	case "git_branch", "dev-git_branch":
		return GitBranch
	case "git_commit", "dev-git_commit":
		return GitCommit
	case "git_compare", "dev-git_compare":
		return GitCompare
	case "git_merge", "dev-git_merge":
		return GitMerge
	case "git_pull_request", "dev-git_pull_request":
		return GitPullRequest
	case "gitbook", "dev-gitbook":
		return Gitbook
	case "github", "dev-github":
		return Github
	case "github_badge", "dev-github_badge":
		return GithubBadge
	case "github_full", "dev-github_full":
		return GithubFull
	case "githubactions", "dev-githubactions":
		return Githubactions
	case "githubcodespaces", "dev-githubcodespaces":
		return Githubcodespaces
	case "gitlab", "dev-gitlab":
		return Gitlab
	case "gitpod", "dev-gitpod":
		return Gitpod
	case "gitter", "dev-gitter":
		return Gitter
	case "gnu", "dev-gnu":
		return Gnu
	case "go", "dev-go":
		return Go
	case "godot", "dev-godot":
		return Godot
	case "goland", "dev-goland":
		return Goland
	case "google", "dev-google":
		return Google
	case "googlecloud", "dev-googlecloud":
		return Googlecloud
	case "gradle", "dev-gradle":
		return Gradle
	case "grafana", "dev-grafana":
		return Grafana
	case "grails", "dev-grails":
		return Grails
	case "graphql", "dev-graphql":
		return Graphql
	case "groovy", "dev-groovy":
		return Groovy
	case "grpc", "dev-grpc":
		return Grpc
	case "grunt", "dev-grunt":
		return Grunt
	case "gulp", "dev-gulp":
		return Gulp
	case "hadoop", "dev-hadoop":
		return Hadoop
	case "handlebars", "dev-handlebars":
		return Handlebars
	case "hardhat", "dev-hardhat":
		return Hardhat
	case "harvester", "dev-harvester":
		return Harvester
	case "haskell", "dev-haskell":
		return Haskell
	case "haxe", "dev-haxe":
		return Haxe
	case "helm", "dev-helm":
		return Helm
	case "heroku", "dev-heroku":
		return Heroku
	case "hibernate", "dev-hibernate":
		return Hibernate
	case "homebrew", "dev-homebrew":
		return Homebrew
	case "html5", "dev-html5":
		return Html5
	case "hugo", "dev-hugo":
		return Hugo
	case "ie", "dev-ie":
		return Ie
	case "ifttt", "dev-ifttt":
		return Ifttt
	case "illustrator", "dev-illustrator":
		return Illustrator
	case "influxdb", "dev-influxdb":
		return Influxdb
	case "inkscape", "dev-inkscape":
		return Inkscape
	case "insomnia", "dev-insomnia":
		return Insomnia
	case "intellij", "dev-intellij":
		return Intellij
	case "ionic", "dev-ionic":
		return Ionic
	case "jaegertracing", "dev-jaegertracing":
		return Jaegertracing
	case "jamstack", "dev-jamstack":
		return Jamstack
	case "jasmine", "dev-jasmine":
		return Jasmine
	case "java", "dev-java":
		return Java
	case "javascript", "dev-javascript":
		return Javascript
	case "javascript_alt", "dev-javascript_alt":
		return JavascriptAlt
	case "javascript_badge", "dev-javascript_badge":
		return JavascriptBadge
	case "jeet", "dev-jeet":
		return Jeet
	case "jekyll", "dev-jekyll":
		return Jekyll
	case "jekyll_small", "dev-jekyll_small":
		return JekyllSmall
	case "jenkins", "dev-jenkins":
		return Jenkins
	case "jest", "dev-jest":
		return Jest
	case "jetbrains", "dev-jetbrains":
		return Jetbrains
	case "jetpackcompose", "dev-jetpackcompose":
		return Jetpackcompose
	case "jira", "dev-jira":
		return Jira
	case "jiraalign", "dev-jiraalign":
		return Jiraalign
	case "jquery", "dev-jquery":
		return Jquery
	case "json", "dev-json":
		return Json
	case "jule", "dev-jule":
		return Jule
	case "julia", "dev-julia":
		return Julia
	case "junit", "dev-junit":
		return Junit
	case "jupyter", "dev-jupyter":
		return Jupyter
	case "k3os", "dev-k3os":
		return K3Os
	case "k3s", "dev-k3s":
		return K3S
	case "k6", "dev-k6":
		return K6
	case "kaggle", "dev-kaggle":
		return Kaggle
	case "karatelabs", "dev-karatelabs":
		return Karatelabs
	case "karma", "dev-karma":
		return Karma
	case "kdeneon", "dev-kdeneon":
		return Kdeneon
	case "keras", "dev-keras":
		return Keras
	case "kibana", "dev-kibana":
		return Kibana
	case "knexjs", "dev-knexjs":
		return Knexjs
	case "knockout", "dev-knockout":
		return Knockout
	case "kotlin", "dev-kotlin":
		return Kotlin
	case "krakenjs", "dev-krakenjs":
		return Krakenjs
	case "krakenjs_badge", "dev-krakenjs_badge":
		return KrakenjsBadge
	case "ktor", "dev-ktor":
		return Ktor
	case "kubernetes", "dev-kubernetes":
		return Kubernetes
	case "labview", "dev-labview":
		return Labview
	case "laravel", "dev-laravel":
		return Laravel
	case "latex", "dev-latex":
		return Latex
	case "less", "dev-less":
		return Less
	case "linkedin", "dev-linkedin":
		return Linkedin
	case "linux", "dev-linux":
		return Linux
	case "liquibase", "dev-liquibase":
		return Liquibase
	case "livewire", "dev-livewire":
		return Livewire
	case "llvm", "dev-llvm":
		return Llvm
	case "lodash", "dev-lodash":
		return Lodash
	case "logstash", "dev-logstash":
		return Logstash
	case "lua", "dev-lua":
		return Lua
	case "lumen", "dev-lumen":
		return Lumen
	case "magento", "dev-magento":
		return Magento
	case "mariadb", "dev-mariadb":
		return Mariadb
	case "markdown", "dev-markdown":
		return Markdown
	case "materializecss", "dev-materializecss":
		return Materializecss
	case "materialui", "dev-materialui":
		return Materialui
	case "matlab", "dev-matlab":
		return Matlab
	case "matplotlib", "dev-matplotlib":
		return Matplotlib
	case "maven", "dev-maven":
		return Maven
	case "maya", "dev-maya":
		return Maya
	case "meteor", "dev-meteor":
		return Meteor
	case "meteorfull", "dev-meteorfull":
		return Meteorfull
	case "microsoftsqlserver", "dev-microsoftsqlserver":
		return Microsoftsqlserver
	case "minitab", "dev-minitab":
		return Minitab
	case "mithril", "dev-mithril":
		return Mithril
	case "mobx", "dev-mobx":
		return Mobx
	case "mocha", "dev-mocha":
		return Mocha
	case "modx", "dev-modx":
		return Modx
	case "moleculer", "dev-moleculer":
		return Moleculer
	case "mongodb", "dev-mongodb":
		return Mongodb
	case "mongoose", "dev-mongoose":
		return Mongoose
	case "moodle", "dev-moodle":
		return Moodle
	case "mootools_badge", "dev-mootools_badge":
		return MootoolsBadge
	case "mozilla", "dev-mozilla":
		return Mozilla
	case "msdos", "dev-msdos":
		return Msdos
	case "mysql", "dev-mysql":
		return Mysql
	case "nano", "dev-nano":
		return Nano
	case "neo4j", "dev-neo4j":
		return Neo4J
	case "neovim", "dev-neovim":
		return Neovim
	case "nestjs", "dev-nestjs":
		return Nestjs
	case "netlify", "dev-netlify":
		return Netlify
	case "networkx", "dev-networkx":
		return Networkx
	case "nextjs", "dev-nextjs":
		return Nextjs
	case "nginx", "dev-nginx":
		return Nginx
	case "ngrx", "dev-ngrx":
		return Ngrx
	case "nhibernate", "dev-nhibernate":
		return Nhibernate
	case "nim", "dev-nim":
		return Nim
	case "nimble", "dev-nimble":
		return Nimble
	case "nixos", "dev-nixos":
		return Nixos
	case "nodejs", "dev-nodejs":
		return Nodejs
	case "nodejs_small", "dev-nodejs_small":
		return NodejsSmall
	case "nodemon", "dev-nodemon":
		return Nodemon
	case "nodewebkit", "dev-nodewebkit":
		return Nodewebkit
	case "nomad", "dev-nomad":
		return Nomad
	case "norg", "dev-norg":
		return Norg
	case "notion", "dev-notion":
		return Notion
	case "npm", "dev-npm":
		return Npm
	case "nuget", "dev-nuget":
		return Nuget
	case "numpy", "dev-numpy":
		return Numpy
	case "nuxtjs", "dev-nuxtjs":
		return Nuxtjs
	case "oauth", "dev-oauth":
		return Oauth
	case "objectivec", "dev-objectivec":
		return Objectivec
	case "ocaml", "dev-ocaml":
		return Ocaml
	case "ohmyzsh", "dev-ohmyzsh":
		return Ohmyzsh
	case "okta", "dev-okta":
		return Okta
	case "openal", "dev-openal":
		return Openal
	case "openapi", "dev-openapi":
		return Openapi
	case "opencl", "dev-opencl":
		return Opencl
	case "opencv", "dev-opencv":
		return Opencv
	case "opengl", "dev-opengl":
		return Opengl
	case "openstack", "dev-openstack":
		return Openstack
	case "opensuse", "dev-opensuse":
		return Opensuse
	case "opentelemetry", "dev-opentelemetry":
		return Opentelemetry
	case "opera", "dev-opera":
		return Opera
	case "oracle", "dev-oracle":
		return Oracle
	case "ory", "dev-ory":
		return Ory
	case "p5js", "dev-p5js":
		return P5Js
	case "packer", "dev-packer":
		return Packer
	case "pandas", "dev-pandas":
		return Pandas
	case "perl", "dev-perl":
		return Perl
	case "pfsense", "dev-pfsense":
		return Pfsense
	case "phalcon", "dev-phalcon":
		return Phalcon
	case "phoenix", "dev-phoenix":
		return Phoenix
	case "photonengine", "dev-photonengine":
		return Photonengine
	case "photoshop", "dev-photoshop":
		return Photoshop
	case "php", "dev-php":
		return Php
	case "phpstorm", "dev-phpstorm":
		return Phpstorm
	case "playwright", "dev-playwright":
		return Playwright
	case "plotly", "dev-plotly":
		return Plotly
	case "pnpm", "dev-pnpm":
		return Pnpm
	case "podman", "dev-podman":
		return Podman
	case "poetry", "dev-poetry":
		return Poetry
	case "polygon", "dev-polygon":
		return Polygon
	case "portainer", "dev-portainer":
		return Portainer
	case "postcss", "dev-postcss":
		return Postcss
	case "postgresql", "dev-postgresql":
		return Postgresql
	case "postman", "dev-postman":
		return Postman
	case "powershell", "dev-powershell":
		return Powershell
	case "premierepro", "dev-premierepro":
		return Premierepro
	case "prisma", "dev-prisma":
		return Prisma
	case "processing", "dev-processing":
		return Processing
	case "prolog", "dev-prolog":
		return Prolog
	case "prometheus", "dev-prometheus":
		return Prometheus
	case "protractor", "dev-protractor":
		return Protractor
	case "pulsar", "dev-pulsar":
		return Pulsar
	case "pulumi", "dev-pulumi":
		return Pulumi
	case "puppeteer", "dev-puppeteer":
		return Puppeteer
	case "purescript", "dev-purescript":
		return Purescript
	case "putty", "dev-putty":
		return Putty
	case "pycharm", "dev-pycharm":
		return Pycharm
	case "pypi", "dev-pypi":
		return Pypi
	case "pyscript", "dev-pyscript":
		return Pyscript
	case "pytest", "dev-pytest":
		return Pytest
	case "python", "dev-python":
		return Python
	case "pytorch", "dev-pytorch":
		return Pytorch
	case "qodana", "dev-qodana":
		return Qodana
	case "qt", "dev-qt":
		return Qt
	case "quarkus", "dev-quarkus":
		return Quarkus
	case "quasar", "dev-quasar":
		return Quasar
	case "qwik", "dev-qwik":
		return Qwik
	case "r", "dev-r":
		return R
	case "rabbitmq", "dev-rabbitmq":
		return Rabbitmq
	case "rails", "dev-rails":
		return Rails
	case "railway", "dev-railway":
		return Railway
	case "rancher", "dev-rancher":
		return Rancher
	case "raspberry_pi", "dev-raspberry_pi":
		return RaspberryPi
	case "reach", "dev-reach":
		return Reach
	case "react", "dev-react":
		return React
	case "reactbootstrap", "dev-reactbootstrap":
		return Reactbootstrap
	case "reactnavigation", "dev-reactnavigation":
		return Reactnavigation
	case "reactrouter", "dev-reactrouter":
		return Reactrouter
	case "readthedocs", "dev-readthedocs":
		return Readthedocs
	case "realm", "dev-realm":
		return Realm
	case "rect", "dev-rect":
		return Rect
	case "redhat", "dev-redhat":
		return Redhat
	case "redis", "dev-redis":
		return Redis
	case "redux", "dev-redux":
		return Redux
	case "renpy", "dev-renpy":
		return Renpy
	case "replit", "dev-replit":
		return Replit
	case "requirejs", "dev-requirejs":
		return Requirejs
	case "rider", "dev-rider":
		return Rider
	case "rocksdb", "dev-rocksdb":
		return Rocksdb
	case "rockylinux", "dev-rockylinux":
		return Rockylinux
	case "rollup", "dev-rollup":
		return Rollup
	case "ros", "dev-ros":
		return Ros
	case "rspec", "dev-rspec":
		return Rspec
	case "rstudio", "dev-rstudio":
		return Rstudio
	case "ruby", "dev-ruby":
		return Ruby
	case "ruby_on_rails", "dev-ruby_on_rails":
		return RubyOnRails
	case "ruby_rough", "dev-ruby_rough":
		return RubyRough
	case "rubymine", "dev-rubymine":
		return Rubymine
	case "rust", "dev-rust":
		return Rust
	case "rxjs", "dev-rxjs":
		return Rxjs
	case "safari", "dev-safari":
		return Safari
	case "salesforce", "dev-salesforce":
		return Salesforce
	case "sanity", "dev-sanity":
		return Sanity
	case "sass", "dev-sass":
		return Sass
	case "scala", "dev-scala":
		return Scala
	case "scalingo", "dev-scalingo":
		return Scalingo
	case "scikitlearn", "dev-scikitlearn":
		return Scikitlearn
	case "sdl", "dev-sdl":
		return Sdl
	case "selenium", "dev-selenium":
		return Selenium
	case "sema", "dev-sema":
		return Sema
	case "sentry", "dev-sentry":
		return Sentry
	case "sequelize", "dev-sequelize":
		return Sequelize
	case "shopware", "dev-shopware":
		return Shopware
	case "shotgrid", "dev-shotgrid":
		return Shotgrid
	case "sketch", "dev-sketch":
		return Sketch
	case "slack", "dev-slack":
		return Slack
	case "smashing_magazine", "dev-smashing_magazine":
		return SmashingMagazine
	case "socketio", "dev-socketio":
		return Socketio
	case "solidity", "dev-solidity":
		return Solidity
	case "solidjs", "dev-solidjs":
		return Solidjs
	case "sonarqube", "dev-sonarqube":
		return Sonarqube
	case "sourcetree", "dev-sourcetree":
		return Sourcetree
	case "spack", "dev-spack":
		return Spack
	case "splunk", "dev-splunk":
		return Splunk
	case "spring", "dev-spring":
		return Spring
	case "spss", "dev-spss":
		return Spss
	case "spyder", "dev-spyder":
		return Spyder
	case "sqlalchemy", "dev-sqlalchemy":
		return Sqlalchemy
	case "sqldeveloper", "dev-sqldeveloper":
		return Sqldeveloper
	case "sqlite", "dev-sqlite":
		return Sqlite
	case "ssh", "dev-ssh":
		return Ssh
	case "stackoverflow", "dev-stackoverflow":
		return Stackoverflow
	case "stata", "dev-stata":
		return Stata
	case "storybook", "dev-storybook":
		return Storybook
	case "streamlit", "dev-streamlit":
		return Streamlit
	case "stylus", "dev-stylus":
		return Stylus
	case "sublime", "dev-sublime":
		return Sublime
	case "subversion", "dev-subversion":
		return Subversion
	case "supabase", "dev-supabase":
		return Supabase
	case "svelte", "dev-svelte":
		return Svelte
	case "swagger", "dev-swagger":
		return Swagger
	case "swift", "dev-swift":
		return Swift
	case "swiper", "dev-swiper":
		return Swiper
	case "symfony", "dev-symfony":
		return Symfony
	case "symfony_badge", "dev-symfony_badge":
		return SymfonyBadge
	case "tailwindcss", "dev-tailwindcss":
		return Tailwindcss
	case "tauri", "dev-tauri":
		return Tauri
	case "tensorflow", "dev-tensorflow":
		return Tensorflow
	case "terminal", "dev-terminal":
		return Terminal
	case "terraform", "dev-terraform":
		return Terraform
	case "tex", "dev-tex":
		return Tex
	case "thealgorithms", "dev-thealgorithms":
		return Thealgorithms
	case "threedsmax", "dev-threedsmax":
		return Threedsmax
	case "threejs", "dev-threejs":
		return Threejs
	case "titaniumsdk", "dev-titaniumsdk":
		return Titaniumsdk
	case "tomcat", "dev-tomcat":
		return Tomcat
	case "tortoisegit", "dev-tortoisegit":
		return Tortoisegit
	case "towergit", "dev-towergit":
		return Towergit
	case "traefikmesh", "dev-traefikmesh":
		return Traefikmesh
	case "traefikproxy", "dev-traefikproxy":
		return Traefikproxy
	case "travis", "dev-travis":
		return Travis
	case "trello", "dev-trello":
		return Trello
	case "trpc", "dev-trpc":
		return Trpc
	case "twitter", "dev-twitter":
		return Twitter
	case "typescript", "dev-typescript":
		return Typescript
	case "typo3", "dev-typo3":
		return Typo3
	case "ubuntu", "dev-ubuntu":
		return Ubuntu
	case "uml", "dev-uml":
		return Uml
	case "unifiedmodelinglanguage", "dev-unifiedmodelinglanguage":
		return Unifiedmodelinglanguage
	case "unity", "dev-unity":
		return Unity
	case "unity_small", "dev-unity_small":
		return UnitySmall
	case "unix", "dev-unix":
		return Unix
	case "unrealengine", "dev-unrealengine":
		return Unrealengine
	case "uwsgi", "dev-uwsgi":
		return Uwsgi
	case "v8", "dev-v8":
		return V8
	case "vagrant", "dev-vagrant":
		return Vagrant
	case "vala", "dev-vala":
		return Vala
	case "vault", "dev-vault":
		return Vault
	case "vercel", "dev-vercel":
		return Vercel
	case "vertx", "dev-vertx":
		return Vertx
	case "vim", "dev-vim":
		return Vim
	case "visualbasic", "dev-visualbasic":
		return Visualbasic
	case "visualstudio", "dev-visualstudio":
		return Visualstudio
	case "vite", "dev-vite":
		return Vite
	case "vitejs", "dev-vitejs":
		return Vitejs
	case "vitess", "dev-vitess":
		return Vitess
	case "vitest", "dev-vitest":
		return Vitest
	case "vscode", "dev-vscode":
		return Vscode
	case "vsphere", "dev-vsphere":
		return Vsphere
	case "vuejs", "dev-vuejs":
		return Vuejs
	case "vuestorefront", "dev-vuestorefront":
		return Vuestorefront
	case "vuetify", "dev-vuetify":
		return Vuetify
	case "vyper", "dev-vyper":
		return Vyper
	case "wasm", "dev-wasm":
		return Wasm
	case "webflow", "dev-webflow":
		return Webflow
	case "weblate", "dev-weblate":
		return Weblate
	case "webpack", "dev-webpack":
		return Webpack
	case "webstorm", "dev-webstorm":
		return Webstorm
	case "windows", "dev-windows":
		return Windows
	case "windows11", "dev-windows11":
		return Windows11
	case "woocommerce", "dev-woocommerce":
		return Woocommerce
	case "wordpress", "dev-wordpress":
		return Wordpress
	case "xamarin", "dev-xamarin":
		return Xamarin
	case "xcode", "dev-xcode":
		return Xcode
	case "xd", "dev-xd":
		return Xd
	case "xml", "dev-xml":
		return Xml
	case "yaml", "dev-yaml":
		return Yaml
	case "yarn", "dev-yarn":
		return Yarn
	case "yii", "dev-yii":
		return Yii
	case "yugabytedb", "dev-yugabytedb":
		return Yugabytedb
	case "yunohost", "dev-yunohost":
		return Yunohost
	case "zend", "dev-zend":
		return Zend
	case "zig", "dev-zig":
		return Zig
	default:
		return nil
	}
}

// AllGlyphIDs returns an iterator over all the IDs of the glyphs in the class.
func AllGlyphIDs() iter.Seq[string] {
	return func(yield func(string) bool) {
		for glyph := range AllGlyphs() {
			if !yield(glyph.ID) {
				return
			}
		}
	}
}

// AllGlyphFullIDs returns an iterator over all the full IDs of the glyphs in the class.
func AllGlyphFullIDs() iter.Seq[string] {
	return func(yield func(string) bool) {
		for glyph := range AllGlyphs() {
			if !yield(glyph.FullID()) {
				return
			}
		}
	}
}
