// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.
//
// Glyphs are also under various licenses, as documented here:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/LICENSE
//
// Generated using glyph info from:
//  * https://github.com/ryanoasis/nerd-fonts/blob/master/glyphnames.json
//
// Additional information:
//  * Website: https://www.nerdfonts.com
//  * Development Website: https://github.com/ryanoasis/nerd-fonts
//  * Version: 3.4.0

// Package extra contains the Nerd Fonts glyphs for the "extra" class.
package extra

import "github.com/lrstanley/go-nf"

const (
	// Class is the name of the class.
	Class nf.Class = "extra"

	// Version is the version of the Nerd Fonts project which this package was generated from.
	Version = "3.4.0"
)

const (
	ProgressEmptyLeft  nf.Glyph = "" //  ("\uee00") represents the "extra-progress_empty_left" glyph.
	ProgressEmptyMid   nf.Glyph = "" //  ("\uee01") represents the "extra-progress_empty_mid" glyph.
	ProgressEmptyRight nf.Glyph = "" //  ("\uee02") represents the "extra-progress_empty_right" glyph.
	ProgressFullLeft   nf.Glyph = "" //  ("\uee03") represents the "extra-progress_full_left" glyph.
	ProgressFullMid    nf.Glyph = "" //  ("\uee04") represents the "extra-progress_full_mid" glyph.
	ProgressFullRight  nf.Glyph = "" //  ("\uee05") represents the "extra-progress_full_right" glyph.
	ProgressSpinner1   nf.Glyph = "" //  ("\uee06") represents the "extra-progress_spinner_1" glyph.
	ProgressSpinner2   nf.Glyph = "" //  ("\uee07") represents the "extra-progress_spinner_2" glyph.
	ProgressSpinner3   nf.Glyph = "" //  ("\uee08") represents the "extra-progress_spinner_3" glyph.
	ProgressSpinner4   nf.Glyph = "" //  ("\uee09") represents the "extra-progress_spinner_4" glyph.
	ProgressSpinner5   nf.Glyph = "" //  ("\uee0a") represents the "extra-progress_spinner_5" glyph.
	ProgressSpinner6   nf.Glyph = "" //  ("\uee0b") represents the "extra-progress_spinner_6" glyph.
)
