// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.

package extra

import (
	"iter"
	"slices"

	"github.com/lrstanley/go-nf"
)

var allGlyphs = []*nf.Glyph{
	ProgressEmptyLeft,
	ProgressEmptyMid,
	ProgressEmptyRight,
	ProgressFullLeft,
	ProgressFullMid,
	ProgressFullRight,
	ProgressSpinner1,
	ProgressSpinner2,
	ProgressSpinner3,
	ProgressSpinner4,
	ProgressSpinner5,
	ProgressSpinner6,
}

// AllGlyphs returns an iterator over all the glyphs in the extra class.
func AllGlyphs() iter.Seq[*nf.Glyph] {
	return slices.Values(allGlyphs)
}

// ByID finds a glyph by its ID within the class.
func ByID(id string) *nf.Glyph {
	switch id {
	case "progress_empty_left", "extra-progress_empty_left":
		return ProgressEmptyLeft
	case "progress_empty_mid", "extra-progress_empty_mid":
		return ProgressEmptyMid
	case "progress_empty_right", "extra-progress_empty_right":
		return ProgressEmptyRight
	case "progress_full_left", "extra-progress_full_left":
		return ProgressFullLeft
	case "progress_full_mid", "extra-progress_full_mid":
		return ProgressFullMid
	case "progress_full_right", "extra-progress_full_right":
		return ProgressFullRight
	case "progress_spinner_1", "extra-progress_spinner_1":
		return ProgressSpinner1
	case "progress_spinner_2", "extra-progress_spinner_2":
		return ProgressSpinner2
	case "progress_spinner_3", "extra-progress_spinner_3":
		return ProgressSpinner3
	case "progress_spinner_4", "extra-progress_spinner_4":
		return ProgressSpinner4
	case "progress_spinner_5", "extra-progress_spinner_5":
		return ProgressSpinner5
	case "progress_spinner_6", "extra-progress_spinner_6":
		return ProgressSpinner6
	default:
		return nil
	}
}

// AllGlyphIDs returns an iterator over all the IDs of the glyphs in the class.
func AllGlyphIDs() iter.Seq[string] {
	return func(yield func(string) bool) {
		for glyph := range AllGlyphs() {
			if !yield(glyph.ID) {
				return
			}
		}
	}
}

// AllGlyphFullIDs returns an iterator over all the full IDs of the glyphs in the class.
func AllGlyphFullIDs() iter.Seq[string] {
	return func(yield func(string) bool) {
		for glyph := range AllGlyphs() {
			if !yield(glyph.FullID()) {
				return
			}
		}
	}
}
